### ISSUE TITLE
Can't retrieve all my favorites

### ISSUE THREAD

**Issue by davidfischer-ch** [flyingrub/scdl#102]
Hello,

I have about 1000+ favorites but scdl only detects 381 of them (probably the oldest ones).
Do you have any idea why? Is it a pagination issue? Thanks for investigating.

At commit c71c4e8477657946645db31f3e221e94f222aa51.

    $ scdl me -c -f

    Soundcloud Downloader

    Hello davidfischer-ch!

    Retrieving the favorites of user davidfischer-ch...
    Retrieved 381 favorites
    Favorite n°1 of 381

**Comment by jmcken8** [comment]
Yeah looks like pagination. Soundcloud recently-ish modified their API to use linked pagination rather than using offsets... https://developers.soundcloud.com/docs/api/guide#pagination
