### ISSUE TITLE
Error on setting tag when song has no proper picture

### ISSUE THREAD

**Issue by piks** [flyingrub/scdl#113]
example of nonproper picture https://soundcloud.com/djb2matcher/nightcore-hangover
#92 same error as this
OS: linux mint 17.3

**Comment by flyingrub** [comment]
it works well here. Can you provide more information on how you installed it and the output of the script ?

**Comment by piks** [comment]
Installed via pip3 on terminal then proceeded to try and grab a playlist, it got everything fine but it said "Error trying to set the tags..." every so often.

**Comment by piks** [comment]
heres an example http://i.imgur.com/lXzd3CH.png

**Comment by flyingrub** [comment]
can you try to `pip3 install scdl --upgrade`

**Comment by piks** [comment]
tried it, just responded with an error 
`ImportError: No module named 'pypandoc'`
upon installing pypandoc via pip3 it errored with
`raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or install pypandoc wheels with included pandoc.
upon installing pandoc the pip3 error tree expands to 
`    TypeError: 'dict_keys' object does not support indexing
`
Not sure where to go from here.

**Comment by xnrx** [comment]
Try this `sudo pip3 install pypandoc`

**Comment by piks** [comment]
That is what caused the pydoc not found error

**Comment by flyingrub** [comment]
can you try at https://github.com/flyingrub/scdl/commit/1e8de9f72a252ea8c789d2ffa879513dba9b373a with the `--debug` flag ?

**Comment by piks** [comment]
Confirmed working, completely purged scdl folder from /usr/local/lib/python3.5/site-packages/scdl reinstalled via pip3 and copied the scdl.py file from the repo directly and it seemed to fix it. Obtained file without picture(which is good because song contained no picture) and no error setting tags. Problem seems to be fixed. Thanks for the help
