### ISSUE TITLE
Fix the pipy page.

### ISSUE THREAD

**Issue by flyingrub** [flyingrub/scdl#116]
https://pypi.python.org/pypi/scdl
Currently the pipy page is totaly broken, it should have a way to convert .md to .rst easily.
https://github.com/flyingrub/scdl/commit/43f2fe71a6178ed83214f4ce59f2a64db36b00a2 didn't fix anything

**Comment by xnrx** [comment]
https://gist.github.com/anonymous/2a38a9ed90bb5df0b2bc

**Comment by xnrx** [comment]
sorry, this cant be a fix at any point. pipy should automatically translate md to rst? what if you keep two versions if nothing going to help?

**Comment by xnrx** [comment]
#117

**Comment by flyingrub** [comment]
i would prefer keeping the .md file and generating the .rst on the fly.

**Comment by xnrx** [comment]
anyway, you can temporary use this

**Comment by xnrx** [comment]
You tried this? https://pypi.python.org/pypi/pyandoc/

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/43f2fe71a6178ed83214f4ce59f2a64db36b00a2

**Comment by xnrx** [comment]
This is two different libs. `pyandoc` and `pypandoc`. This error is really weird.

**Comment by thijstriemstra** [comment]
What about:

```
[metadata]
description-file = README.md
```

in setup.cfg?

**Comment by thijstriemstra** [comment]
So https://github.com/flyingrub/scdl/pull/172 was pointless, and apparently converting it to .rst is also pointless, only realtime conversion makes sense apparently.

**Comment by flyingrub** [comment]
already tried a few commit later but it didn't worked well.
