### ISSUE TITLE
name 'download_all_of_user' is not defined

### ISSUE THREAD

**Issue by cschmittiey** [flyingrub/scdl#121]
Using latest scdl from this repo, I get this: 
```
[csmith@doctorow music]$ scdl me -f -c --onlymp3
Soundcloud Downloader

Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.5.0.post1', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.4/site-packages/scdl-1.5.0.post1-py3.4.egg/scdl/scdl.py", line 122, in main
NameError: name 'download_all_of_user' is not defined
```

**Comment by lee12jin** [comment]
This function is missing from scdl.py
Same with the other functions that go along with the argument "me" within the function main().

"download_all_of_user" "download_all_of_user_tracks"

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/49a4f17b5ad37695f11c13f05338cf54a58677a0
