### ISSUE TITLE
Some files gets stored wrapped in quotation marks

### ISSUE THREAD

**Issue by raveslave** [flyingrub/scdl#124]
scdl -l https://soundcloud.com/username/ -f
results in saving quite a few songs to disk like this (Mac 10.11)

`"rba final mix jan 23.mp3"`

**Comment by flyingrub** [comment]
Yup, it's a known bug related to the new way we download the track when the
original file is available.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/a059810591b0e02a1cc753f768b5edfaddf7c7cf
