### ISSUE TITLE
no certificate for pypi.python.org

### ISSUE THREAD

**Issue by rupat** [flyingrub/scdl#131]
Hi Guys following problems:

i cant install the script. after some research i get the reason the certificate dont matches. Can someone help me ?

wget https://pypi.python.org/packages/source/c/clint/clint-0.5.1.tar.gz#md5=8afd569f077886e2f4e6cca377da2623
--2016-03-24 13:57:10--  https://pypi.python.org/packages/source/c/clint/clint-0.5.1.tar.gz
Auflösen des Hostnamen pypi.python.org... 185.31.17.223
Verbindungsaufbau zu pypi.python.org|185.31.17.223|:443... verbunden.
FEHLER: Der Common Name »www.python.org« des Zertifikates entspricht nicht dem angeforderten Hostname »pypi.python.org«.
Verwenden Sie »--no-check-certificate«, um zu dem Server »pypi.python.org« eine nicht gesicherte Verbindung aufzubauen.

is there a way to bypass certificate check for python ?

python3 setup.py install
running install
install_dir /usr/local/lib/python3.1/dist-packages/
Checking .pth file support in /usr/local/lib/python3.1/dist-packages/
/usr/bin/python3 -E -c pass
TEST PASSED: /usr/local/lib/python3.1/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to scdl.egg-info/requires.txt
writing scdl.egg-info/PKG-INFO
writing top-level names to scdl.egg-info/top_level.txt
writing dependency_links to scdl.egg-info/dependency_links.txt
writing entry points to scdl.egg-info/entry_points.txt
reading manifest file 'scdl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scdl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-3.1/scdl/utils.py -> build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-3.1/scdl/scdl.py -> build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-3.1/scdl/soundcloud.py -> build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-3.1/scdl/**init**.py -> build/bdist.linux-x86_64/egg/scdl
byte-compiling build/bdist.linux-x86_64/egg/scdl/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/scdl/scdl.py to scdl.pyc
byte-compiling build/bdist.linux-x86_64/egg/scdl/soundcloud.py to soundcloud.pyc
byte-compiling build/bdist.linux-x86_64/egg/scdl/**init**.py to **init**.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/scdl-v1.5.0_3-py3.1.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing scdl-v1.5.0_3-py3.1.egg
removing '/usr/local/lib/python3.1/dist-packages/scdl-v1.5.0_3-py3.1.egg' (and everything under it)
creating /usr/local/lib/python3.1/dist-packages/scdl-v1.5.0_3-py3.1.egg
Extracting scdl-v1.5.0_3-py3.1.egg to /usr/local/lib/python3.1/dist-packages
scdl v1.5.0-3 is already the active version in easy-install.pth
Installing scdl script to /usr/local/bin

Installed /usr/local/lib/python3.1/dist-packages/scdl-v1.5.0_3-py3.1.egg
Processing dependencies for scdl==v1.5.0-3
Searching for clint
Reading http://pypi.python.org/simple/clint/
Best match: clint 0.5.1
Downloading https://pypi.python.org/packages/source/c/clint/clint-0.5.1.tar.gz#md5=8afd569f077886e2f4e6cca377da2623
Processing clint-0.5.1.tar.gz
error: Not a recognized archive type: /tmp/easy_install-AonHr7/clint-0.5.1.tar.gz

**Comment by flyingrub** [comment]
mm i think your version of python and pip is outdated...
what happens if you run `scdl --version` ?

**Comment by rupat** [comment]
?? scdl --version ?

```
scdl -version
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2671, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: clint

```

have now installed via python2

```
python setup.py install
running install
install_dir /usr/local/lib/python2.6/dist-packages/
Checking .pth file support in /usr/local/lib/python2.6/dist-packages/
/usr/bin/python -E -c pass
TEST PASSED: /usr/local/lib/python2.6/dist-packages/ appears to support .pth files
running bdist_egg
running egg_info
writing requirements to scdl.egg-info/requires.txt
writing scdl.egg-info/PKG-INFO
writing top-level names to scdl.egg-info/top_level.txt
writing dependency_links to scdl.egg-info/dependency_links.txt
writing entry points to scdl.egg-info/entry_points.txt
reading manifest file 'scdl.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'scdl.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_py
creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-2.6/scdl/utils.py -> build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-2.6/scdl/scdl.py -> build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-2.6/scdl/soundcloud.py -> build/bdist.linux-x86_64/egg/scdl
copying build/lib.linux-x86_64-2.6/scdl/__init__.py -> build/bdist.linux-x86_64/egg/scdl
byte-compiling build/bdist.linux-x86_64/egg/scdl/utils.py to utils.pyc
byte-compiling build/bdist.linux-x86_64/egg/scdl/scdl.py to scdl.pyc
SyntaxError: ('invalid syntax', ('build/bdist.linux-x86_64/egg/scdl/scdl.py', 63, 22, 'logger.newline = print\n'))

byte-compiling build/bdist.linux-x86_64/egg/scdl/soundcloud.py to soundcloud.pyc
byte-compiling build/bdist.linux-x86_64/egg/scdl/__init__.py to __init__.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/entry_points.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying scdl.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/scdl-v1.5.0_3-py2.6.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing scdl-v1.5.0_3-py2.6.egg
removing '/usr/local/lib/python2.6/dist-packages/scdl-v1.5.0_3-py2.6.egg' (and everything under it)
creating /usr/local/lib/python2.6/dist-packages/scdl-v1.5.0_3-py2.6.egg
Extracting scdl-v1.5.0_3-py2.6.egg to /usr/local/lib/python2.6/dist-packages
SyntaxError: ('invalid syntax', ('/usr/local/lib/python2.6/dist-packages/scdl-v1.5.0_3-py2.6.egg/scdl/scdl.py', 63, 22, 'logger.newline = print\n'))

scdl v1.5.0-3 is already the active version in easy-install.pth
Installing scdl script to /usr/local/bin

Installed /usr/local/lib/python2.6/dist-packages/scdl-v1.5.0_3-py2.6.egg
Processing dependencies for scdl==v1.5.0-3
Searching for clint==0.5.1
Best match: clint 0.5.1
Processing clint-0.5.1-py2.6.egg
clint 0.5.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/clint-0.5.1-py2.6.egg
Searching for requests==2.9.1
Best match: requests 2.9.1
Processing requests-2.9.1-py2.6.egg
requests 2.9.1 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/requests-2.9.1-py2.6.egg
Searching for termcolor==1.1.0
Best match: termcolor 1.1.0
Processing termcolor-1.1.0-py2.6.egg
termcolor 1.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/termcolor-1.1.0-py2.6.egg
Searching for soundcloud==0.5.0
Best match: soundcloud 0.5.0
Processing soundcloud-0.5.0-py2.6.egg
soundcloud 0.5.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/soundcloud-0.5.0-py2.6.egg
Searching for mutagen==1.31
Best match: mutagen 1.31
Processing mutagen-1.31-py2.6.egg
mutagen 1.31 is already the active version in easy-install.pth
Installing moggsplit script to /usr/local/bin
Installing mid3cp script to /usr/local/bin
Installing mutagen-inspect script to /usr/local/bin
Installing mid3iconv script to /usr/local/bin
Installing mid3v2 script to /usr/local/bin
Installing mutagen-pony script to /usr/local/bin

Using /usr/local/lib/python2.6/dist-packages/mutagen-1.31-py2.6.egg
Searching for docopt==0.6.2
Best match: docopt 0.6.2
Processing docopt-0.6.2-py2.6.egg
docopt 0.6.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/docopt-0.6.2-py2.6.egg
Searching for args==0.1.0
Best match: args 0.1.0
Processing args-0.1.0-py2.6.egg
args 0.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/args-0.1.0-py2.6.egg
Searching for simplejson==3.8.2
Best match: simplejson 3.8.2
Processing simplejson-3.8.2-py2.6.egg
simplejson 3.8.2 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/simplejson-3.8.2-py2.6.egg
Searching for fudge==1.1.0
Best match: fudge 1.1.0
Processing fudge-1.1.0-py2.6.egg
fudge 1.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python2.6/dist-packages/fudge-1.1.0-py2.6.egg
Finished processing dependencies for scdl==v1.5.0-3

```

but still getting

```
 scdl --version
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.5.0-3', 'console_scripts', 'scdl')()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python2.6/dist-packages/scdl-v1.5.0_3-py2.6.egg/scdl/scdl.py", line 63
    logger.newline = print
                         ^
SyntaxError: invalid syntax
```

**Comment by rupat** [comment]
after reading tried also the following:

```
pip3 install scdl
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources

```

**Comment by flyingrub** [comment]
try `sudo pip3 install --upgrade pip`

**Comment by rupat** [comment]
`pip3 install --upgrade pip
/usr/local/lib/python3.1/dist-packages/pip-8.1.1-py3.1.egg/pip/_vendor/pkg_resources/__init__.py:87: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
  warnings.warn(msg)
Traceback (most recent call last):
  File "/usr/local/bin/pip3", line 9, in <module>
    load_entry_point('pip==8.1.1', 'console_scripts', 'pip3')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 305, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2244, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 1954, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/local/lib/python3.1/dist-packages/pip-8.1.1-py3.1.egg/pip/__init__.py", line 16, in <module>
    from pip.vcs import git, mercurial, subversion, bazaar  # noqa
  File "/usr/local/lib/python3.1/dist-packages/pip-8.1.1-py3.1.egg/pip/vcs/mercurial.py", line 9, in <module>
    from pip.download import path_to_url
  File "/usr/local/lib/python3.1/dist-packages/pip-8.1.1-py3.1.egg/pip/download.py", line 36, in <module>
    from pip.utils.ui import DownloadProgressBar, DownloadProgressSpinner
  File "/usr/local/lib/python3.1/dist-packages/pip-8.1.1-py3.1.egg/pip/utils/ui.py", line 15, in <module>
    from pip._vendor.progress.bar import Bar, IncrementalBar
  File "/usr/local/lib/python3.1/dist-packages/pip-8.1.1-py3.1.egg/pip/_vendor/progress/bar.py", line 48
    empty_fill = u'∙'
                      ^
SyntaxError: invalid syntax
`

**Comment by rupat** [comment]
which pip3
/usr/local/bin/pip3

/usr/bin/python3 --version
Python 3.1.3

**Comment by flyingrub** [comment]
your install of python3 / pip3 is broken you need to fix it in order to install scdl correctly.

**Comment by flyingrub** [comment]
This issue is not related to scdl itself. Closing.
