### ISSUE TITLE
Nice job, Malware Link on Your README 

### ISSUE THREAD

**Issue by aes512** [flyingrub/scdl#132]
Your stupid Token link leads to this:

https://www.virustotal.com/en/url/9c76320a56f295b92253efc1c38098e12cfefd05b5e91e54415c368b0bf5dba6/analysis/1458957853/

Nice job, reported to Github administrators.

**Comment by flyingrub** [comment]
Wtf ?

**Comment by flyingrub** [comment]
mm, my domain has expired. I'm going to move it to another one soon.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/027f6008d5cb4ce655ba3a56c1a1be96d12ffb0b
