### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-psr842sr/scdl/

### ISSUE THREAD

**Issue by Stiggia** [flyingrub/scdl#134]
I'm on ubuntu 16.04 and i get this error on install attemp

stiggia@stiggia-X555LJ:~$ pip3 install scdl
Collecting scdl
  Downloading scdl-1.5.0.post3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-psr842sr/scdl/
stiggia@stiggia-X555LJ:~$ sudo pip3 install scdl
The directory '/home/stiggia/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/stiggia/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting scdl
  Downloading scdl-1.5.0.post3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-rhycob3j/scdl/

**Comment by flyingrub** [comment]
`pip3 install setuptools`

**Comment by Stiggia** [comment]
This solve thank u Ronan

**Comment by Stiggia** [comment]
No is not true.

stiggia@stiggia-X555LJ:~$ pip3 install scdl
Collecting scdl
Collecting clint (from scdl)
Collecting soundcloud (from scdl)
Collecting termcolor (from scdl)
Collecting docopt (from scdl)
Collecting mutagen (from scdl)
Collecting requests (from scdl)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting args (from clint->scdl)
Collecting fudge>=1.0.3 (from soundcloud->scdl)
Collecting simplejson>=2.0 (from soundcloud->scdl)
Installing collected packages: args, clint, fudge, requests, simplejson, soundcloud, termcolor, docopt, mutagen, scdl
Successfully installed args-0.1.0 clint-0.5.1 docopt-0.6.2 fudge-1.1.0 mutagen-1.31 requests-2.9.1 scdl-1.5.0.post3 simplejson-3.8.2 soundcloud-0.5.0 termcolor-1.1.0
Segmentation fault (core dumped)
stiggia@stiggia-X555LJ:~$ scdl
scdl: command not found

**Comment by flyingrub** [comment]
mm try to install it from github

**Comment by flyingrub** [comment]
any news ?

**Comment by Stiggia** [comment]
I don't know why I've not tryed it for a long time but look like it works.
I don't even remember how i solved, i'm sorry!
