### ISSUE TITLE
Typo in "Downloading original" statement

### ISSUE THREAD

**Issue by michaelbartholic** [flyingrub/scdl#136]
When downloading a track that has an original file available, the terminal returns the statement "Downloading the orginal file." as opposed to the statement "Downloading the _original_ file." as it should. The word "original" is simply missing an "i" character.

<img width="570" alt="typo" src="https://cloud.githubusercontent.com/assets/3936246/14073398/a4df4942-f496-11e5-9ffe-02c73efa08f2.png">

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/4adb799907e9861f1ab1aaea1e0cb48b6cf0d873
