### ISSUE TITLE
Set tracknumbers when downloading playlist.

### ISSUE THREAD

**Issue by insilmaril** [flyingrub/scdl#138]
When downloading a complete playlist, scdl prints "Track°$n", but doesn't set the related track.

Thus some players won't be able to play e.g. an album in correct order...

**Comment by flyingrub** [comment]
there is a .m3u that you can play :)

**Comment by insilmaril** [comment]
Maybe I could play m3u, but not my phone ;-)

Anyway, I think I have a working patch, stay tuned...

**Comment by flyingrub** [comment]
any audioplayer on android have the playlist view where all the m3u detected goes.

**Comment by insilmaril** [comment]
Even the covers go into the mp3 file itself, why not using the existing tag, but an external m3u file?

Just checked in Amarok: the tracknumber track is used to order the tracks of an album. Without it's screwed up.
