### ISSUE TITLE
Impossible to download a playlist

### ISSUE THREAD

**Issue by e2del** [flyingrub/scdl#142]
I'm trying to download this playlist : 
https://soundcloud.com/laurent-garnier/sets/it-is-what-it-is-saison-6
But no one mp3 is downloaded
 So i'm trying to download this : 
https://soundcloud.com/laurent-garnier/iiwii-s6e1?in=laurent-garnier/sets/it-is-what-it-is-saison-6
but i get errors

Debug information : 
scdl -c -l https://soundcloud.com/laurent-garnier/sets/it-is-what-it-is-saison-6 --path /volume1/music/Soundcloud/Laurent\ Garnier/ --debug -p
Soundcloud Downloader
{'--addtofile': False,
 '--debug': True,
 '--error': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--onlymp3': False,
 '--path': '/volume1/music/Soundcloud/Laurent Garnier/',
 '--version': False,
 '-a': False,
 '-c': True,
 '-f': False,
 '-l': 'https://soundcloud.com/laurent-garnier/sets/it-is-what-it-is-saison-6',
 '-o': None,
 '-p': True,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to /volume1/music/Soundcloud/Laurent Garnier...

{'user': {'kind': 'user', 'username': 'laurent garnier', 'last_modified': '2016/04/08 08:40:01 +0000', 'id': 1488, 'permalink': 'laurent-garnier', 'avatar_url': 'https://i1.sndcdn.com/avatars-000095152869-yeaus3-large.jpg', 'permalink_url': 'http://soundcloud.com/laurent-garnier', 'uri': 'https://api.soundcloud.com/users/1488'}, 'purchase_url': None, 'id': 163701035, 'purchase_title': None, 'title': 'It Is What It Is - Saison 6', 'tracks': [], 'license': 'all-rights-reserved', 'permalink_url': 'http://soundcloud.com/laurent-garnier/sets/it-is-what-it-is-saison-6', 'playlist_type': None, 'created_with': {'name': 'SoundCloud.com', 'kind': 'app', 'id': 46941, 'external_url': '', 'creator': 'soundcloud', 'permalink_url': 'http://developers.soundcloud.com/', 'uri': 'https://api.soundcloud.com/apps/46941'}, 'release_month': None, 'duration': 43542782, 'genre': 'radio', 'embeddable_by': 'all', 'track_count': 6, 'release_year': None, 'artwork_url': 'https://i1.sndcdn.com/artworks-000135559099-hyiy8x-large.jpg', 'tag_list': '', 'label_id': None, 'created_at': '2015/11/09 14:35:51 +0000', 'streamable': True, 'ean': None, 'description': "Laurent Garnier's monthly radioshow on www.radiomeuh.com", 'sharing': 'public', 'label_name': None, 'uri': 'https://api.soundcloud.com/playlists/163701035', 'user_id': 1488, 'kind': 'playlist', 'last_modified': '2015/11/09 14:39:31 +0000', 'type': None, 'release': None, 'permalink': 'it-is-what-it-is-saison-6', 'downloadable': False, 'release_day': None}

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/61479bd7457cf8a6d1fb586eb48c702290f45d26 fixed

**Comment by flyingrub** [comment]
by the way : good music taste ;)

**Comment by e2del** [comment]
Thanks the fix works great !
Good music is better with a good downloader, thx !
