### ISSUE TITLE
Options not working

### ISSUE THREAD

**Issue by e2del** [flyingrub/scdl#143]
The option --hide-progress not working, the option seems not to be used in the code.
If i use --error, i have a blank line added between each track downloaded.

**Comment by e2del** [comment]
for the option --hide--progress a possible patch :

```
        if arguments["--hide-progress"] is  None:
            hide = False
        else:
            hide = True
        with temp as f:
            total_length = int(r.headers.get('content-length'))
            for chunk in progress.bar(
                r.iter_content(chunk_size=1024),
                expected_size=(total_length/1024) + 1,
                hide = hide
            ):
                if chunk:
                    f.write(chunk)
                    f.flush()
```

**Comment by e2del** [comment]
blank lines are from : 
```
    logger.newline()
    logger.info('\n {0} Downloaded.\n'.format(filename))
    logger.newline()
```
may-be replaced by 
`logger.info('\n {0} Downloaded.\n'.format(filename))`

and also here : 
```
logger.newline()
    if arguments['-l']:
```

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/251ec14bc908b626f0974d4172b06b9684e810dd fixed the hide-progress

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/ae3cff24fac9ef027a1d616ef0e5cfd97c7b4101 don't seems to fix the newline issue :/

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/ae3cff24fac9ef027a1d616ef0e5cfd97c7b4101 fixes it after correctly installing it :p
