### ISSUE TITLE
Dynamically get client_id

### ISSUE THREAD

**Issue by uahim** [flyingrub/scdl#148]
v1.5.0-3 stopped working all of sudden, so I upgraded to v1.5.2.

now this happens: instead of downloading the actual mp3, the downloader reports to having successfully downloaded a track which actually is a JSON file with 187 bytes of size and the following contents. tried with 3 different tracks.
[json.txt](https://github.com/flyingrub/scdl/files/293734/json.txt)

ideas?
OS is Win32 with Python 3.4.3 installed if that matters

**Comment by flyingrub** [comment]
Can you share the full command you used when this happened ?

**Comment by uahim** [comment]
attached
[command.txt](https://github.com/flyingrub/scdl/files/294404/command.txt)

**Comment by flyingrub** [comment]
{"errors":[{"meta":{"rate_limit":{"bucket":"by-client","max_nr_of_requests":65000,"time_window":"PT24H","name":"plays"},"remaining_requests":0,"reset_time":"2016/06/02 07:20:38 +0000"}}]}

mm i think the clientID has no more request until tomorrow...
We will need a new way to get clientID dynamically.

**Comment by cRaZy-bisCuiT** [comment]
That would be nice! I could not download anything AT ALL. :(

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/692b74cc0bc2d339725df1308c082a0df2d7c0b9 a workaround for now.
