### ISSUE TITLE
Invalid Syntax Error: logger.newline = print

### ISSUE THREAD

**Issue by Trig0n** [flyingrub/scdl#149]
Heya,
just reinstalled scdl, which was working pretty good before i resetup my laptop.
Now I'm getting this syntax error.

File "scdl.py", line 63
    logger.newline = print
                         ^
SyntaxError: invalid syntax

Was there an update, which bugged it, or am I missing something?

//Nevermind. I'm retarded. 
//Thinking before opening a Ticket.
//Was using Python 2.7 instead of 3

**Comment by flyingrub** [comment]
You were using python2 ;)

**Comment by Trig0n** [comment]
Yeah...That happens when you get up and try to do stuff without coffee..

Good work on scdl. Probs mate.
