### ISSUE TITLE
Connection Reseted By Peer when downloading large number of files / -c Continue does not work on this cases

### ISSUE THREAD

**Issue by mcaseiro** [flyingrub/scdl#150]
When you use for example download -a (all musics from this artist) we can have large numbers of tracks, I've be seem 700. But in the middle of the process, like 100 or more tracks downloaded we got an Connection Reseted by Peer, then scdl reopen the connection and start from zero again.

Would by too much of overhead for each track open a new  connection with a max number of try out and maybe jump to next track with a txt report of files error?

And one other thing could be check the files if they've been downloaded when scdl restart connection automaticaly after the reset, but no, it start download from the beginning.

**Comment by flyingrub** [comment]
It open one connection for each download.
So if one track fail the other are still on your HDD and you can use the -c option.
I don't really understand your problem...

**Comment by mcaseiro** [comment]
I think I understand what was the problem when scdl find a new playlist the
number of the track begans again 1 2 3 making myself believe that was the
confusion, can you please confirm that for each playlist found on -a option
the track number on the terminal start a new count from zero for that
playlist?

Thanks for the reply,

Best Regards

Mario Caseiro

**Comment by flyingrub** [comment]
yes :)

**Comment by laur89** [comment]
@mcaseiro or @flyingrub - close the issue?
