### ISSUE TITLE
DL complete profile likes - Not downloading in complete.

### ISSUE THREAD

**Issue by hemantchhabra** [flyingrub/scdl#153]
Hello.
I wanted to know if there's anything I'm doing wrong.
I'm using the '-f' command to download all my soundcloud profile liked songs. In total it shows I have 598 likes, but it stops at 258. Is there anything I'm doing wrong?
![screen shot 2016-08-05 at 11 42 58](https://cloud.githubusercontent.com/assets/5680977/17427894/d11d7fac-5b01-11e6-87f7-d5e6c7e6158e.png)

**Comment by flyingrub** [comment]
Use `-c`
