### ISSUE TITLE
[FR] add possibility to sync playlist/likes

### ISSUE THREAD

**Issue by laur89** [flyingrub/scdl#154]
Add something like -s/--sync option to sync the working dir with the downloadable content (say likes list); all files in the working dir not matching a file in likes list should also be deleted.

**Comment by Supruim** [comment]
I would definitely love that, but then its better to run it on a server to sync unliked tracks and delete them and download new songs you just liked.

**Comment by CodeNameTheOnlyOne** [comment]
the best way would just be a flag to remove all items that do not match what you are downloading(playlist/likes/etc) then just have it run in a cron job at your desired frequency.
i guess you could do this currently if you just deleted all items prior to runing the download but that would cause it to redownload all items every time.

**Comment by Supruim** [comment]
wouldn't it be better to make a list of likes and compare it every 5 or ten minutes, if a item doesn't match the list it simply gets deleted and if it inst on the client side list it would download it.

**Comment by CodeNameTheOnlyOne** [comment]
that is basicly what i am saying.
im not familiar with the code but does scdl not keep a running list of what it has downloaded in the session.
you would just run something like >scdl -cf -l https://soundcloud.com/stelouse --remove
and that would remove any files in the working dir that do not match the playlist and download and new ones.
then you set that to run with cron or some other scheduler at your desired frequency.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/6d1b07d2b81d19ef79b01f64ff1dc389f72f4fa2 should fix this :)

**Comment by jarikmarwede** [comment]
The feature that was added works in that it deletes the files that were not downloaded by the current execution of the program. But what I think would be better or at least an option for an additional feature is to only delete files that are not contained in the list entered into the program. Currently files that are still in the list but were already downloaded previously are deleted with the --remove option.

**Comment by flyingrub** [comment]
This should not be the case... Can you open a new issue about it ?

**Comment by jarikmarwede** [comment]
Oh ok, yeah I opened #299
