### ISSUE TITLE
Add support for private tracks / playlists

### ISSUE THREAD

**Issue by timpulver** [flyingrub/scdl#156]
Private links contain a token at the end of the URL, e.g. `https://soundcloud.com/someuser/sometrack/s-Hxi42`

See [Sharing a private track or playlist within SoundCloud](http://shareandembed.help.soundcloud.com/customer/portal/articles/2167144-sharing-a-private-track-or-playlist-within-soundcloud).

**Comment by flyingrub** [comment]
```
0 fly@Minotoor ~ $ scdl -l https://soundcloud.com/flyingrub/ether/s-rfb8L
Soundcloud Downloader

Found a track
Downloading Ether
[################################] 1503/1503 - 00:00:02
Settings tags...

Ether.mp3 Downloaded.
```
It works here with a private link, can you describle your use case ?

**Comment by timpulver** [comment]
All working now, just needed to update scdl, thanks!
Very handy feature when receiving demos to listen in the subway!
