### ISSUE TITLE
Auth token

### ISSUE THREAD

**Issue by cuonic** [flyingrub/scdl#157]
Hi,

I've made an alternative site for retrieving Soundcloud auth tokens to use your profile data, here's what you need to do to get things working:

* `git clone https://github.com/flyingrub/scdl.git && cd scdl`
* Edit `scdl.py` and replace the value of `scdl_client_id` (line 71) with `a06b61f88c8297cc5abe6167a2d4c519`
* Edit `client.py` and replace the value of `scdl_client_id` (line 5) with `a06b61f88c8297cc5abe6167a2d4c519`
* `cd .. && sudo python3 setup.py install`
* Go to: https://dev.vm0.eu/scdl/
* Click "Connect with Soundclound"
* Login to Soundcloud (if not already authenticated) and click "Connect"
* Copy your access token and paste as the value of `auth_token` in `~/.config/scdl/scdl.cfg`

Now you can go ahead and download your playlists and favourites !

**Comment by flyingrub** [comment]
http://flyingrub.github.io/scdl/, i don't know why my old website worked, but i couldn't get it to work with gh-pages. If you can have a look :).

**Comment by cuonic** [comment]
That's exactly what I was looking for ! I'll get rid of my app :) Could you update the README with the link for others ?

**Comment by cuonic** [comment]
It's your callback URL that's the problem, you need to change it to: http://flyingrub.github.io/scdl/callback.html and have it call the original window's connection success callback.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/3419acf082265b55ffa760a13eba6f321312decd
