### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2

### ISSUE THREAD

**Issue by Franciscoseipel** [flyingrub/scdl#159]
`Traceback (most recent call last):

  File "/usr/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.5.2', 'console_scripts', 'scdl')()

  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 132, in main
    parse_url(arguments['-l'])

  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 208, in parse_url
    download_playlist(item)

  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 302, in download_playlist
    download_track(track_raw, playlist['title'], playlist_file)

  File "/usr/lib/python3.5/site-packages/scdl/scdl.py", line 337, in download_track
    title = title.encode('utf-8', 'ignore').decode(sys.stdout.encoding)

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 10: ordinal not in range(128)
`
Song: https://soundcloud.com/syrex-music/syrex-nightcore-toxic-2016-s3rl
System: arm Arch linux 
When downloading the song I get this error. I think the → triggers it.

**Comment by flyingrub** [comment]
```
0 fly@Minotoor ~ $ scdl -l https://soundcloud.com/syrex-music/syrex-nightcore-toxic-2016-s3rl
Soundcloud Downloader

Found a track
Downloading Nightcore → S3RL - Toxic 2016
[################################] 2461/2461 - 00:00:02
Settings tags...

Nightcore → S3RL - Toxic 2016.mp3 Downloaded.
```
it works well here on Arch too...
can you run `locale -a` ?

**Comment by Franciscoseipel** [comment]
# locale -a
C
POSIX
de_DE
de_DE.iso88591
deutsch
en_US.utf8
german

**Comment by flyingrub** [comment]
could you try to set your default language to : `de_DE.utf8` and relaunch the script ?

**Comment by Franciscoseipel** [comment]
year it works now.
Had to add `export LANG=de_DE.utf8` to `/etc/locale.conf`
Thanks
