### ISSUE TITLE
Possible to download liked/favorited playlists?

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#160]
Hi there, just discovered scdl and I'm finding it incredibly useful so far.

I have an issue that I searched for a bit but couldn't find an answer for after a few glances.

Is there a way to download all my _favorited/liked playlists_? That is, sets made by other people. On desktop, those playlists can be reached at https://soundcloud.com/you/sets (which also includes my own sets).

If there is support for this, perhaps a auth/token is necessary to reach them?

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/e862d2b2e02200002d7fb1ca6e872ae4bb9ef808
use `scdl me -m`
