### ISSUE TITLE
Authentication issues after updating to 1.6

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#162]
I could use scdl before updating to 1.6, with the following command:

`scdl -l https://soundcloud.com/myuser -f -c --addtofile --path my/dl/path`

After updating, I get the error:

```
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/users/xxxxx/favorites?limit=200&offset=0&client_id=xxxxxxxxxxxxxxxxxxxxxx&linked_partitioning=1&oauth_token=
```

I tried to create a token and add it to `$HOME/.config/scdl/` with the contents:

```
[scdl]
auth_token = 123-my-token-456
```

When running:

`scdl me -f -c --addtofile --path my/dl/path`

or

`scdl -l me -f -c --addtofile --path my/dl/path`

I get the error:

`Are you sure scdl.cfg is in $HOME/.config/scdl/ ?`

(I am pretty sure it is).

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/bf81d2337e2d4c24b00bbc266a99697ea4e0ca26 Thx for the report ! fixed ;)

**Comment by flyingrub** [comment]
For the issue with your .cfg can you check that the permission of the file are set correctly ?

**Comment by winterflags** [comment]
Updated to 1.6.1.

Now I'm getting the message:

` Are you sure scdl.cfg is in $HOME/.config/scdl/ ?`

even when running without `me`, using `scdl -l https://soundcloud.com/myuser -f -c --addtofile --path my/dl/path`. Shouldn't that bypass the need to check for the config file?

I'm not sure what the proper permissions should be, but they are:

```
pwd
/Users/me/.config/scdl`
-rw-r--r--  1 me  staff   53 Sep 27 19:45 scdl.cfg
```

**Comment by flyingrub** [comment]
try to delete it ?

**Comment by winterflags** [comment]
Yes, deleting the file seems to make the application work with the link username.

But `scdl -l https://soundcloud.com/me -p -c` no longer downloads liked tracks. Instead it starts downloading playlists on the profile...

**Comment by flyingrub** [comment]
It's `-f` to download liked track

**Comment by winterflags** [comment]
I did chmod 777 on scdl.cfg but still get this error:

`Are you sure scdl.cfg is in $HOME/.config/scdl/?`

Also deleted the file and running `scdl` recreates the `scdl.cfg` file, so it's in the right place...

**Comment by flyingrub** [comment]
I suggest you create a new issue :)
I will try to investigate

**Comment by winterflags** [comment]
To be honest, it was a part of this issue but you closed it ;)
