### ISSUE TITLE
Are you sure scdl.cfg is in $HOME/.config/scdl/?

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#163]
Updated to 1.6.1.

Now I'm getting the message:

`Are you sure scdl.cfg is in $HOME/.config/scdl/ ?`

even when running without `me`, using `scdl -l https://soundcloud.com/myuser -f -c --addtofile --path my/dl/path`. Shouldn't that bypass the need to check for the config file?

I'm not sure what the proper permissions should be, but they are:

```
pwd
/Users/me/.config/scdl
-rw-r--r--  1 me  staff   53 Sep 27 19:45 scdl.cfg
```

I've tried chmod to 777, with the same results. I've also deleted the file and had `scdl` recreate it (which it does everytime you start `scdl`). Same result with both.

The situation seems to be like this, regardless of whether there is a token id or not in the file.

**Comment by winterflags** [comment]
I should perhaps also add that when I run:

`scdl -l https://soundcloud.com/me -m  --addtofile --path /my/path`

….nothing happens except the "flags/commands" help line.

Maybe it's because `-m` only works when run with `me`, like `me -m`.

But running with `me` give me the `scdl.config` problem described above :)

**Comment by flyingrub** [comment]
any update on this issue ? @winterflags have you retried recently ?

**Comment by winterflags** [comment]
@flyingrub I just tried now with the latest update through pip, it seems to be working nicely!

Was able to download my liked playlists/albums with `scdl me -m`, really sweet.
