### ISSUE TITLE
zsh: command not found: scdl

### ISSUE THREAD

**Issue by alextrastero** [flyingrub/scdl#164]
Installed with `pip3 install scdl` but says command not found. However this file exists `$HOME/.config/scdl/scdl.cfg`. I would add to $PATH but I don't know where python packages are installed.

**Comment by flyingrub** [comment]
What OS did you use ?

**Comment by alextrastero** [comment]
@flyingrub OSX 10.11

**Comment by Tmplt** [comment]
If you install it via `pip3 install --user scdl`, `scdl` can be found at `~/.local/bin/scdl`.

This also keeps directories meant for your package manager's packages clean.

**Comment by alextrastero** [comment]
@Tmplt thanks that solved it

**Comment by alextrastero** [comment]
Actually not, do I have to add it manually to $PATH?
![screen shot 2016-10-11 at 08 15 01](https://cloud.githubusercontent.com/assets/4152819/19260568/e9d86ed6-8f8a-11e6-937c-cf77edf8d20f.png)

**Comment by alextrastero** [comment]
![screen shot 2016-10-11 at 08 16 45](https://cloud.githubusercontent.com/assets/4152819/19260590/144061ba-8f8b-11e6-8413-e06890133cee.png)

**Comment by alextrastero** [comment]
No worries, found another package that does work: https://github.com/Miserlou/SoundScrape.
SoundScrape installs with pip, maybe my issue was pip3?
