### ISSUE TITLE
Set file timestamp to pubdate

### ISSUE THREAD

**Issue by PeteLawler** [flyingrub/scdl#166]
I see in the SC page code that they push out '<time pubdate>' which would appear to be the publish date. Would be great if the file timestamp, when saved, can have that time and date set so that things can be sorted in chronological order.

**Comment by flyingrub** [comment]
Does the program exit normaly ? Could you provide an output sample ?

**Comment by Chaz6** [comment]
If it helps, youtube_dl does this.
