### ISSUE TITLE
Download only new tracks 

### ISSUE THREAD

**Issue by MichaelBac** [flyingrub/scdl#167]
Hi, 

Is it possible to download only new tracks and not all uploaded tracks? 

Is it possible to copy the Song description and url to a txt file? 

Respect for ur work.

**Comment by flyingrub** [comment]
> Is it possible to download only new tracks and not all uploaded tracks?
Yes you can use the `-c` option and it will only donwload the track that doesn't exist locally. ;)

> Is it possible to copy the Song description and url to a txt file?
No for now.
