### ISSUE TITLE
Add ability to download from batch file

### ISSUE THREAD

**Issue by N07070** [flyingrub/scdl#168]
Hello,

It would be great to be able to batch download from a file with scdl, much like youtube-dl does it. Could it be possible ? 

I'll try to look into it.

Thanks !

**Comment by uahim** [comment]
you could just use batch file or oneliner/shell script, depending on your OS. something like `for /F "tokens=*" %%A in (list_of_urls.txt) do scdl --with-your-switches %%A` within a batch file should work on all Windows versions

**Comment by flyingrub** [comment]
@N07070, does @uahim's answer satisfy you ?

**Comment by N07070** [comment]
I'll try as soon as I have time to write a new option to be able to use a text file like youtube-dl. But for the mean time, the solution will do.

**Comment by flyingrub** [comment]
I don't feel like this need to be integrated to scdl as @uahim is a one line bash script. So I'm closing this for now.
