### ISSUE TITLE
Download full tracks with Soundcloud GO account

### ISSUE THREAD

**Issue by YohannLYD** [flyingrub/scdl#169]
Here's a feature that could be interesting.
I have a Soundcloud GO account and I would like to use this script to download some tracks that are only available with a GO account.

The auth_token / "me" option seems only made to download our own tracks. I tried to download some "GO" tracks byt I only get the first 30 seconds of the song (as if I was not subscribed).

How would it be possible to use the token to download the full tracks ?

**Comment by MaxLeiter** [comment]
👍  same question

**Comment by flyingrub** [comment]
With soundcloud blocking our client_id we cannot use the access token anymore. So it will be difficult to link scdl to a soundcloud account.

**Comment by PSandro** [comment]
Is there any update on this? :thinking:
