### ISSUE TITLE
Option to add other name to duplicate file name 

### ISSUE THREAD

**Issue by voyeg3r** [flyingrub/scdl#175]
With very long playlists it is hard to remember older names, so for this reason, an option to save duplicated names would come in handy.

**Comment by flyingrub** [comment]
i'm not sure i fully understand your problem. You would like to force the download if the file already exist ?

**Comment by flyingrub** [comment]
@voyeg3r any feedback would be helpful :)

**Comment by flyingrub** [comment]
You can use the `-c` option to continue the download if a file is already downloaded.
Feel free to reopen this issue if I misinterpreted it :) .
