### ISSUE TITLE
Can't download tracks with offset more than 200 due to limit. Gets 403 Error.

### ISSUE THREAD

**Issue by vishnumaiea** [flyingrub/scdl#178]
I was trying to download the liked list of 813 tracks (though SCDL showed only 792). The download was interrupted due to "duplicate file" error at 555th track. Then I tried adding "-o 555" with the next command but received a "403 Forbidden" error. Later I found that I can't download a track with a queue number greater than "200" in a large track list. Any offset value greater than 200 resulted in the 403 error. I know this is due to the "pagination" limit. But can you guys create workaround ? :)

![image](https://cloud.githubusercontent.com/assets/10383395/24068878/e2a1e730-0bbf-11e7-8c20-a4c60b9c8ed7.png)

**Comment by perchard** [comment]
+1

**Comment by flyingrub** [comment]
For now a workaround could be to use the `-c` option that will skip all the already downloaded file.

**Comment by winterflags** [comment]
+1

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/58460c2907c2cf82f70c1d4f4e3e63a5c7f568ce fixed :)
