### ISSUE TITLE
Scdl downloads 0:00 

### ISSUE THREAD

**Issue by lucciisgithub** [flyingrub/scdl#179]
Scdl downloads album work, song titles, everything but the actual audio of the song. In my Music it shows songs have a length of 0:00

**Comment by flyingrub** [comment]
Hi ! Could you provide some log of a failed download ?

**Comment by lucciisgithub** [comment]
I found the error, the file Scdl.cfg has two variables. PATH and AUTH Token I have to provide an auth token for  downloading. Heres a log of the scdl with --debug flag 
-debug         
Soundcloud Downloader                                      
{'--addtofile': False,                                     
 '--debug': True,                                          
 '--error': False,                                         
 '--help': False,                                          
 '--hide-progress': False,                                 
 '--hidewarnings': False,                                  
 '--max-size': None,                                       
 '--min-size': None,                                       
 '--onlymp3': False,                                       
 '--path': None,                                           
 '--version': False,                                       
 '-a': False,                                              
 '-c': False,                                              
 '-f': False,                                              
 '-l': 'https://soundcloud.com/liluzivert/sets/lil-uzi-vert-vs-the-world',                                            
 '-m': False,                                              
 '-o': None,                                               
 '-p': False,                                              
 '-s': False,                                              
 '-t': False,                                              
 'me': False}                                              
Downloading to /home/phablet...
https://api.soundcloud.com/playlists/216191541?client_id=bed20744714e9c5962c351efe15840ff                             
{'type': None, 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'kind': 'user', 'username': 'LIL UZI VERT'}, 'streamable': True, 'uri': 'https://api.soundcloud.com/playlists/216191541', 'user_id': 10494998, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158345000-byxu9e-large.jpg', 'track_count': 9, 'id': 216191541, 'sharing': 'public', 'tracks': [{'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158341341-oebiyg-large.jpg', 'playback_count': 1051565, 'id': 259266135, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 183416, 'permalink_url': 'http://soundcloud.com/liluzivert/canadian-goose-produced-by-maaly-raw', 'video_url': None, 'tag_list': 'liluzi liluzivert cannon drama generationnow', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/02/23 02:33:37 +0000', 'title': 'Canadian Goose [Produced By Maaly Raw]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'canadian-goose-produced-by-maaly-raw', 'uri': 'https://api.soundcloud.com/tracks/259266135', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259266135/attachments', 'label_id': None, 'original_content_size': 6983318, 'created_at': '2016/04/15 18:15:57 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/a7F52080APBF_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 643, 'duration': 218272, 'stream_url': 'https://api.soundcloud.com/tracks/259266135/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158335897-jv9lem-large.jpg', 'playback_count': 1354494, 'id': 259259260, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 209256, 'permalink_url': 'http://soundcloud.com/liluzivert/hi-roller-produced-by-maaly-raw', 'video_url': None, 'tag_list': 'liluzi liluzivert cannon generationnow drama', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/02/20 17:42:29 +0000', 'title': 'Hi Roller [Produced by Maaly Raw]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'hi-roller-produced-by-maaly-raw', 'uri': 'https://api.soundcloud.com/tracks/259259260', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259259260/attachments', 'label_id': None, 'original_content_size': 8844086, 'created_at': '2016/04/15 17:29:06 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/4nMe6VU4pwg1_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 621, 'duration': 276427, 'stream_url': 'https://api.soundcloud.com/tracks/259259260/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-uxuTx28ZEffk-0-large.jpg', 'playback_count': 19423062, 'id': 245673410, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': 4, 'genre': 'Hip Hop', 'label_name': 'Generation Now/Atlantic', 'favoritings_count': 1183711, 'permalink_url': 'http://soundcloud.com/liluzivert/money-longer-radio-rip', 'video_url': None, 'tag_list': '', 'downloadable': False, 'purchase_title': 'Buy On ITUNES', 'last_modified': '2017/03/21 11:21:33 +0000', 'title': 'Money Longer', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': 2016, 'bpm': None, 'permalink': 'money-longer-radio-rip', 'uri': 'https://api.soundcloud.com/tracks/245673410', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/245673410/attachments', 'label_id': None, 'original_content_size': 7960031, 'created_at': '2016/02/06 01:57:45 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/gMRljH6srr2k_m.png', 'download_count': 0, 'key_signature': None, 'release_day': 1, 'kind': 'track', 'commentable': True, 'purchase_url': 'https://itunes.apple.com/us/artist/lil-uzi-vert/id940710524', 'comment_count': 10599, 'duration': 199019, 'stream_url': 'https://api.soundcloud.com/tracks/245673410/stream', 'description': '“When I’m with my girl we’re Pharrell and Vashtie\nDat means we are not lasting”… ++++ Money Longer'}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158336937-thg2cz-large.jpg', 'playback_count': 1142025, 'id': 259260342, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': '', 'favoritings_count': 180813, 'permalink_url': 'http://soundcloud.com/liluzivert/grab-the-wheel-produced-by-don-cannon-co-produced-by-cubeatz', 'video_url': None, 'tag_list': 'liluzi liluzivert generationnow cannon drama', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/03/20 23:44:37 +0000', 'title': 'Grab The Wheel [Produced by Don Cannon / Co Produced By CuBeatz]', 'original_format': 'mp3', 'state': 'finished', 'isrc': '', 'release_year': None, 'bpm': None, 'permalink': 'grab-the-wheel-produced-by-don-cannon-co-produced-by-cubeatz', 'uri': 'https://api.soundcloud.com/tracks/259260342', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259260342/attachments', 'label_id': None, 'original_content_size': 11828244, 'created_at': '2016/04/15 17:36:24 +0000', 'release': '', 'user_id': 10494998, 'track_type': '', 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/kR3OG5QeYU2n_m.png', 'download_count': 0, 'key_signature': '', 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 586, 'duration': 295732, 'stream_url': 'https://api.soundcloud.com/tracks/259260342/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158334289-tcyj15-large.jpg', 'playback_count': 12163587, 'id': 259258214, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 1045236, 'permalink_url': 'http://soundcloud.com/liluzivert/you-was-right-produced-by-metro-boomin', 'video_url': None, 'tag_list': '"metro boomin" liluzivert liluzi', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/03/21 15:30:48 +0000', 'title': 'You Was Right [Produced By Metro Boomin]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'you-was-right-produced-by-metro-boomin', 'uri': 'https://api.soundcloud.com/tracks/259258214', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259258214/attachments', 'label_id': None, 'original_content_size': 5247132, 'created_at': '2016/04/15 17:21:51 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/jlCAoPxay9Ty_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 8496, 'duration': 164011, 'stream_url': 'https://api.soundcloud.com/tracks/259258214/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158333925-mwz5il-large.jpg', 'playback_count': 1017173, 'id': 259257756, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 176468, 'permalink_url': 'http://soundcloud.com/liluzivert/baby-are-you-home-produced-by-metro-boomin', 'video_url': None, 'tag_list': 'metroboomin liluzivert liluzi trap cannon dram generationnow', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/03/17 03:32:13 +0000', 'title': 'Baby Are You Home [Produced By Metro Boomin]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'baby-are-you-home-produced-by-metro-boomin', 'uri': 'https://api.soundcloud.com/tracks/259257756', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259257756/attachments', 'label_id': None, 'original_content_size': 7374550, 'created_at': '2016/04/15 17:18:44 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/7gBaxNNYW34S_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 528, 'duration': 230499, 'stream_url': 'https://api.soundcloud.com/tracks/259257756/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158348578-eh3zyq-large.jpg', 'playback_count': 5024153, 'id': 259273264, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': '', 'favoritings_count': 540594, 'permalink_url': 'http://soundcloud.com/liluzivert/ps-qs-produced-by-don-cannon', 'video_url': None, 'tag_list': 'liluzi liluzivert generationnow cannon', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/03/21 01:21:49 +0000', 'title': 'Ps & Qs [Produced By Don Cannon]', 'original_format': 'mp3', 'state': 'finished', 'isrc': '', 'release_year': None, 'bpm': None, 'permalink': 'ps-qs-produced-by-don-cannon', 'uri': 'https://api.soundcloud.com/tracks/259273264', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259273264/attachments', 'label_id': None, 'original_content_size': 8863868, 'created_at': '2016/04/15 19:04:16 +0000', 'release': '', 'user_id': 10494998, 'track_type': '', 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/C2tvH3tSqxtp_m.png', 'download_count': 0, 'key_signature': '', 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 2983, 'duration': 221617, 'stream_url': 'https://api.soundcloud.com/tracks/259273264/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158340818-3x594l-large.jpg', 'playback_count': 773153, 'id': 259265503, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 126146, 'permalink_url': 'http://soundcloud.com/liluzivert/team-rocket-produced-by-don-cannon-and-lyle-leduff', 'video_url': None, 'tag_list': 'liluzi liluzivert generationnow cannon drama', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/03/19 18:19:09 +0000', 'title': 'Team Rocket [Produced by Don Cannon And Lyle LeDuff]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'team-rocket-produced-by-don-cannon-and-lyle-leduff', 'uri': 'https://api.soundcloud.com/tracks/259265503', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259265503/attachments', 'label_id': None, 'original_content_size': 6596304, 'created_at': '2016/04/15 18:11:26 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/qyEQ0kdYZVO8_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 287, 'duration': 206177, 'stream_url': 'https://api.soundcloud.com/tracks/259265503/stream', 'description': ''}, {'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158334589-kxyoow-large.jpg', 'playback_count': 539963, 'id': 259258567, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 84959, 'permalink_url': 'http://soundcloud.com/liluzivert/i-dont-care-produced-by-wondagurl', 'video_url': None, 'tag_list': 'liluzi liluzivert love lovesong', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/03/20 15:10:36 +0000', 'title': 'Scott And Ramona [Produced By Wondagurl]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'i-dont-care-produced-by-wondagurl', 'uri': 'https://api.soundcloud.com/tracks/259258567', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259258567/attachments', 'label_id': None, 'original_content_size': 7084479, 'created_at': '2016/04/15 17:24:11 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/3WcBozakITZR_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 270, 'duration': 221433, 'stream_url': 'https://api.soundcloud.com/tracks/259258567/stream', 'description': ''}], 'downloadable': False, 'ean': None, 'description': '++++\nLIL UZI VERT Vs. THE WORLD\n++++\n\nReleased By \nGeneration Now 2016', 'release_month': 4, 'genre': 'Hip-hop & Rap', 'license': 'all-rights-reserved', 'created_at': '2016/04/15 18:31:39 +0000', 'label_name': 'Generation Now 2016', 'release_year': 2016, 'release': None, 'tag_list': 'Rap liluzi liluzivert generationnow cannon drama trap', 'playlist_type': None, 'release_day': 14, 'label_id': None, 'purchase_title': None, 'last_modified': '2016/04/15 19:05:57 +0000', 'title': 'LIL UZI VERT Vs. THE WORLD', 'kind': 'playlist', 'permalink_url': 'http://soundcloud.com/liluzivert/sets/lil-uzi-vert-vs-the-world', 'purchase_url': None, 'duration': 2033187, 'permalink': 'lil-uzi-vert-vs-the-world', 'embeddable_by': 'all'}                                                       
Found a playlist
{'streamable': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000158341341-oebiyg-large.jpg', 'playback_count': 1051565, 'id': 259266135, 'sharing': 'public', 'embeddable_by': 'all', 'release_month': None, 'genre': 'Hip-hop & Rap', 'label_name': None, 'favoritings_count': 183416, 'permalink_url': 'http://soundcloud.com/liluzivert/canadian-goose-produced-by-maaly-raw', 'video_url': None, 'tag_list': 'liluzi liluzivert cannon drama generationnow', 'downloadable': False, 'purchase_title': None, 'last_modified': '2017/02/23 02:33:37 +0000', 'title': 'Canadian Goose [Produced By Maaly Raw]', 'original_format': 'mp3', 'state': 'finished', 'isrc': None, 'release_year': None, 'bpm': None, 'permalink': 'canadian-goose-produced-by-maaly-raw', 'uri': 'https://api.soundcloud.com/tracks/259266135', 'user': {'avatar_url': 'https://a1.sndcdn.com/images/default_avatar_large.png', 'kind': 'user', 'permalink_url': 'http://soundcloud.com/liluzivert', 'permalink': 'liluzivert', 'uri': 'https://api.soundcloud.com/users/10494998', 'last_modified': '2017/03/09 15:59:03 +0000', 'id': 10494998, 'username': 'LIL UZI VERT'}, 'attachments_uri': 'https://api.soundcloud.com/tracks/259266135/attachments', 'label_id': None, 'original_content_size': 6983318, 'created_at': '2016/04/15 18:15:57 +0000', 'release': None, 'user_id': 10494998, 'track_type': None, 'license': 'all-rights-reserved', 'waveform_url': 'https://w1.sndcdn.com/a7F52080APBF_m.png', 'download_count': 0, 'key_signature': None, 'release_day': None, 'kind': 'track', 'commentable': True, 'purchase_url': None, 'comment_count': 643, 'duration': 218272, 'stream_url': 'https://api.soundcloud.com/tracks/259266135/stream', 'description': ''}           
Track n°1
Downloading Canadian Goose [Produced By Maaly Raw]
filename : Canadian Goose [Produced By Maaly Raw].mp3
https://cf-media.sndcdn.com/a7F52080APBF.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vYTdGNTIwODBBUEJGLjEyOC5tcDMiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0OTAxMjE3NTN9fX1dfQ__&Signature=DUS8jNWwNyAfgJasfxQn6oX58axx793ZA~WGYvtuNpJ7fkzk8v2XZmJ56Qh3ZBPxruIiTVzn4-3KHSmK5TISzrMI-p6kFXpJbZU5b9K~ABs4cicJGTN1qLwleYX~Tmq~RC-9UukRONHFHeKgarOeVTprxx9q7KncJeVTnf6mbwLCit5IXshPQjYN~QVO9gWmt1-NPZXfkX7KTDqDxFkcQFauFF0Mrad76tQMNFjsPzkF21gxPj9yl1Mwvu3gi~K3f1vORF3pXG0Ool8DR~C5dB8UXbEUUw-bGf6YW9fa3kYW9-c8KKWiqUda1Lp1rVCXserUj~5OWUyaFjirj4l-~g__&Key-Pair-Id=APKAJAGZ7VMH2PFPW6UQ                         
[################################] 3411/3411 - 00:00:01
Settings tags...
