### ISSUE TITLE
FIX pip3 install does nothing

### ISSUE THREAD

**Issue by allanlaal** [flyingrub/scdl#180]
package is not installed:

	allan@L4:~$ pip3 install scdl
	Collecting scdl
	  Downloading scdl-1.6.4.tar.gz
	Collecting docopt (from scdl)
	  Downloading docopt-0.6.2.tar.gz
	Collecting mutagen (from scdl)
	  Downloading mutagen-1.37.tar.gz (912kB)
		100% |████████████████████████████████| 921kB 308kB/s 
	Collecting termcolor (from scdl)
	  Downloading termcolor-1.1.0.tar.gz
	Collecting requests (from scdl)
	  Downloading requests-2.13.0-py2.py3-none-any.whl (584kB)
		100% |████████████████████████████████| 593kB 385kB/s 
	Collecting clint (from scdl)
	  Downloading clint-0.5.1.tar.gz
	Collecting args (from clint->scdl)
	  Downloading args-0.1.0.tar.gz
	Building wheels for collected packages: scdl, docopt, mutagen, termcolor, clint, args
	  Running setup.py bdist_wheel for scdl ... done
	  Stored in directory: /home/allan/.cache/pip/wheels/92/a8/0b/6217aad349d00de22e3c40da6623be67d302d917cb96ac8f5d
	  Running setup.py bdist_wheel for docopt ... done
	  Stored in directory: /home/allan/.cache/pip/wheels/b2/16/5f/c33a2bb5f2dce71205f8e65cbfd05647d79d441282be31fd82
	  Running setup.py bdist_wheel for mutagen ... done
	  Stored in directory: /home/allan/.cache/pip/wheels/d2/99/7a/49007bed098faaed83d9b802386f4b31d6babc30f354ed8ff7
	  Running setup.py bdist_wheel for termcolor ... done
	  Stored in directory: /home/allan/.cache/pip/wheels/de/f7/bf/1bcac7bf30549e6a4957382e2ecab04c88e513117207067b03
	  Running setup.py bdist_wheel for clint ... done
	  Stored in directory: /home/allan/.cache/pip/wheels/aa/65/4a/a0bceb0a6bee518b1dace4c803f24c4ac8febe55bdca0f14ed
	  Running setup.py bdist_wheel for args ... done
	  Stored in directory: /home/allan/.cache/pip/wheels/0a/e0/66/35419f9f9ee41099a3631f0f308b9604bd1ffeabc066d69070
	Successfully built scdl docopt mutagen termcolor clint args
	Installing collected packages: docopt, mutagen, termcolor, requests, args, clint, scdl
	Successfully installed args clint docopt mutagen-1.31 requests-2.9.1 scdl termcolor
	You are using pip version 8.1.1, however version 9.0.1 is available.
	You should consider upgrading via the 'pip install --upgrade pip' command.
	allan@L4:~$

**Comment by flyingrub** [comment]
I don't see any problem on your log ?
