### ISSUE TITLE
Track Image

### ISSUE THREAD

**Issue by hXtreme** [flyingrub/scdl#183]
Add optional parameters to include track image into the mp3 file metadata, or alternatively use playlist thumbnail as track image for all files downloaded from a playlist.
#enhancement

**Comment by flyingrub** [comment]
The track image is already added to the track as id3tag. Could you provide more information on this issue ?

**Comment by hXtreme** [comment]
On checking the tag data, I find the image present but the Image doesn't show up in either Groove or Windows Media Player. AIMP sucessfully displays the image.
![scdlgroove](https://cloud.githubusercontent.com/assets/22425371/24820117/77e12fcc-1bb5-11e7-8c8a-c08114bc880c.JPG)
![scdltag](https://cloud.githubusercontent.com/assets/22425371/24820119/77e35086-1bb5-11e7-9962-2d09889aed8f.JPG)
![scdlwmp](https://cloud.githubusercontent.com/assets/22425371/24820118/77e152a4-1bb5-11e7-8029-4624a5507952.JPG)
![scdlaimp](https://cloud.githubusercontent.com/assets/22425371/24820116/77df2ec0-1bb5-11e7-9c2b-fbc76312de61.JPG)

So the issue must be that the image probably doesn't comply with some Microsoft Standard. I'll verify whether the image data shows up on my mobile.

**Comment by flyingrub** [comment]
@hXtreme could we close this issue ? It seems related to windows media player and not scdl itself. ❓

**Comment by hXtreme** [comment]
Okay, fine with me. One can just write a small script to fix this
compatibility problem.
So just in case, instead of closing it can you make it into something along
the lines of optional fix or todo sometime later.

**Comment by flyingrub** [comment]
What kind of small script could fix this ? If you managed to fix feel free to open a PR or share you fix here :)

**Comment by hXtreme** [comment]
I have my finals right now so can't really help directly but my idea is:
1. Extract cover image from the downloaded file.
2. Encode image to a compatible format (probably using ImageMagick)
3. Set the encoded image as cover

I haven't done much research on it but the following looked helpful to me:
[https://github.com/ImageMagick/ImageMagick](ImageMagik)
[https://www.howtogeek.com/109369/how-to-quickly-resize-convert-modify-images-from-the-linux-terminal/](A short tutorial on how easy it is to use)
[http://stackoverflow.com/a/39316853](Adding the cover)
