### ISSUE TITLE
Add a way to download private playlist

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#190]
I've seen references to the `-m` flag, and I'm indeed using it in a scdl script, but I can't see in the manual/help what it's supposed to do.

I know that it's used when downloading all my playlists via `me`. 

_(I'm currently trying to download only a specific hidden playlist created by myself, and trying to find out if `-m` can be useful for that. `scdl me -l [url]` doesn't work)._

**Comment by flyingrub** [comment]
The `-m` option is like `-p` but also download the playlist you liked.

**Comment by flyingrub** [comment]
You can use the share link to download it with `scdl -l`. It contains some random character after the name of the playlist.

**Comment by flyingrub** [comment]
Downloading using the share link works (and also allow to download private song) so closing this one.
