### ISSUE TITLE
invalid_client: The client identifier provided is invalid.

### ISSUE THREAD

**Issue by ltjdym** [flyingrub/scdl#192]
When I try to authenticate here: [https://flyingrub.github.io/scdl/#] i get this error:

"invalid_client: The client identifier provided is invalid."
web address: https://soundcloud.com/connect?state=SoundCloud_Dialog_b9a32&client_id=bed20744714e9c5962c351efe15840ff&redirect_uri=https%3A%2F%2Fflyingrub.github.io%2Fscdl%2Fcallback.html&response_type=code_and_token&scope=non-expiring&display=popup

**Comment by danPixl** [comment]
It's happening for me as well - in the mean time, use this: https://dev.vm0.eu/scdl/

**Comment by flyingrub** [comment]
mm sounds like soundcloud banned my client_id.

**Comment by flyingrub** [comment]
@danPixl Do you allow me to take your clientID and ship it with scdl ?

**Comment by danPixl** [comment]
It's not mine, that site was made by @liamjack - I just found it when looking for an alternative.

**Comment by liamjack** [comment]
Feel free to use the `client_id` used on https://dev.vm0.eu/scdl/.

It'll be banned sooner or later, better make the most of it !

**Comment by flyingrub** [comment]
thanks @liamjack !
Could you change your callback url to https://flyingrub.github.io/scdl/callback.html ?

**Comment by liamjack** [comment]
@flyingrub It appears not, I have no possibility of modifying or deleting any "apps", I can only see the list:

![capture d ecran de 2017-06-17 21-50-40](https://user-images.githubusercontent.com/821228/27255854-45a1e6a8-53a7-11e7-984a-233bab2df4a6.png)

And they've locked down their application process, moving to Google Forms with a manual 1 month processing period:

![capture d ecran de 2017-06-17 21-53-28](https://user-images.githubusercontent.com/821228/27255867-87c7f18a-53a7-11e7-8d1d-f472ad60dd0d.png)

**Comment by ltjdym** [comment]
working thanks!

**Comment by DrPugsley** [comment]
Looks like either they banned that client_id as well or I'm just having problems on my end (hopefully the latter). I'm getting this message whenever I try to download:

401 Client Error: Unauthorized for url: https://api-v2.soundcloud.com/profile/soundcloud:users:226218541?limit=200&offset=0&linked_partitioning=1&client_id=bed20744714e9c5962c351efe15840ff

**Comment by flyingrub** [comment]
You need to install the latest github version.

**Comment by Mopok** [comment]
Doesn't look like  https://dev.vm0.eu/scdl/ is working anymore. Is there a way to download likes without needing authorization?

**Comment by liamjack** [comment]
@Mopok Indeed, Soundcloud have killed my API key. Good luck finding another key before they shut down ;)

**Comment by Mopok** [comment]
Ha, yea don't think luck will help much here. But likes don't need authentication to get. So I guess a workaround for my problem could be done.

**Comment by flyingrub** [comment]
Try to switch the client id in `__init__.py`

**Comment by flyingrub** [comment]
fixed https://github.com/flyingrub/scdl/commit/08317287b615a0bcf874de0751238e1184abc599

**Comment by pyxelr** [comment]
@flyingrub I think the problem reappeared. I've been using scdl for a few months, and suddenly yesterday I received the 401 error. Interestingly, for some of the tunes, I can download the file in .mp extension, which is not usable.
![2019-11-26_20-21-04](https://user-images.githubusercontent.com/30161753/69665248-49ecac00-108a-11ea-8c99-0c09467da624.png)

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/issues/289#issuecomment-559146519
