### ISSUE TITLE
401 Client Error Unauthorized for url

### ISSUE THREAD

**Issue by altmank** [flyingrub/scdl#194]
HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/me?oauth_token=&client_id=bed20744714e9c5962c351efe15840ff

Is this client_id banned? How do I get it to use a new one?

**Comment by flyingrub** [comment]
duplicate https://github.com/flyingrub/scdl/issues/192

We are changing the client_id.

**Comment by 0x4a** [comment]
I have the same happening as of now:

> requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/555142530/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/issues/292#issuecomment-572865132 ?

**Comment by 0x4a** [comment]
> [#292 (comment)](https://github.com/flyingrub/scdl/issues/292#issuecomment-572865132) ?

Yes, this does the trick.
Don't know why I didn't find that issue in the first place... Thanks!
