### ISSUE TITLE
Information request: "The original file has no download left"

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#195]
Requesting information about the message when running scdl:
> "The original file has no download left" _[followed by a Stream mp3 download]_.

Perhaps add info to the `man/help` or in this thread?

---

More specifically, I'm wondering what will happen if a _DOWNLOAD_ (_DL_) track on Soundcloud was previously enabled but has since been disabled by the uploader, and `-c` flag is used when running through a list where the  _DL file_ previously was downloaded to a local folder.

It seems that `scdl` doesn't skip the track but instead downloads the _Stream file_ (non-DL) to the folder. Will the _Stream file_ overwrite the _DL file_, or keep both files?

I wasn't able to find any duplicates of _Stream files_ and _DL files_ on my drive or in my favorites list, so I wasn't able to test the outcome myself.

**Comment by flyingrub** [comment]
it will keep both tracks. The same thing happens if the uploader change the name of the file. :/

**Comment by flyingrub** [comment]
@winterflags can we close this issue ?

**Comment by winterflags** [comment]
@flyingrub Yes absolutely, sorry!
