### ISSUE TITLE
Failing to get auth_token from soundcloud

### ISSUE THREAD

**Issue by vboufleur** [flyingrub/scdl#197]
Accessing https://flyingrub.github.io/scdl/ and clicking on "Connect with Soundcloud" is returning a page written only "Connected successfully !" and with this URL: 

https://dev.vm0.eu/scdl/callback.html?error=redirect_uri_mismatch&error_description=The+redirection+URI+provided+does+not+match+a+pre-registered+value.&state=SoundCloud_Dialog_4158b#

Checking back the flyingrub.github.io page I saw that auth_token wasn't set.

**Comment by Satevg** [comment]
Same problem.

**Comment by otisscott** [comment]
I am also getting the same error

**Comment by flyingrub** [comment]
use https://dev.vm0.eu/scdl/ to get an access token.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/2187c529064a351b93400fea9013d3dd31cef232

**Comment by Di9** [comment]
@flyingrub dev.vm0.eu/scdl/ is dead too :(

**Comment by alirezaabdi01** [comment]
any new websites?
