### ISSUE TITLE
Still getting 401 client error

### ISSUE THREAD

**Issue by DrPugsley** [flyingrub/scdl#199]
I'm not seeing any other open issues for this, so I guess it's just me at this point having the problem, and I'm not really sure why. Here's my output after trying to download [this profile](https://soundcloud.com/mrcreepypasta)

[~/scdl]$ scdl -l https://soundcloud.com/mrcreepypasta -a
Soundcloud Downloader
Error resolving url, retrying...
Found a user profile
Retrieving all tracks and reposts of user Creepypasta Storytime...
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 11, in <module>
    load_entry_point('scdl==1.6.4', 'console_scripts', 'scdl')()
  File "/home/abradolf/.local/lib/python3.5/site-packages/scdl/scdl.py", line 159, in main
    parse_url(arguments['-l'])
  File "/home/abradolf/.local/lib/python3.5/site-packages/scdl/scdl.py", line 247, in parse_url
    download(item, 'all', 'tracks and reposts')
  File "/home/abradolf/.local/lib/python3.5/site-packages/scdl/scdl.py", line 283, in download
    ressources = client.get_collection(dl_url, token)
  File "/home/abradolf/.local/lib/python3.5/site-packages/scdl/client.py", line 19, in get_collection
    response.raise_for_status()
  File "/home/abradolf/.local/lib/python3.5/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-v2.soundcloud.com/profile/soundcloud:users:21534608?limit=200&offset=0&linked_partitioning=1&client_id=bed20744714e9c5962c351efe15840ff

This only happens when I try to download a profile; single tracks still work

**Comment by lee12jin** [comment]
+1 I have the same issue. I have v1.6.4.  I think it's consistently reproducable on any profile. For example, trying https://soundcloud.com/thejinlee won't work as I get the exact same error as above.

**Comment by EuanFH** [comment]
This is caused by client ID request limit for the day being reached or soundcloud revoking the client ids because of misuse of the API. I'm going to guess they revoked it for misuses of the API. you can go into the soundcloud developer page create an app and copy the client id then replace the client id in the __init__.py with the one you just copied then the application will work.

**Comment by MegaNarwhal** [comment]
It appears SoundCloud is currently manually approving the creation of applications and the page says it can take up to 30 days for the application to be approved. If you did finally get a client ID, I'm sure it would be revoked if you downloaded more than a few tracks with it in a short time. Not sure what can be done about this.

**Comment by EuanFH** [comment]
Good thing I have one when I was developing something else with the soundcloud api. It used to be automatic I assume they did the 30 day waiting thing to crack down on people creating applications like this. I managed to download all 1500 likes I had in an hour. so I assume if you aren't downloading a stupid amount it should be fine.

**Comment by flyingrub** [comment]
I just updated the pypi version. It should works now !

**Comment by crvfts** [comment]
I'm receiving this error now as well. Did a git pull, still happening.
