### ISSUE TITLE
Fresh install error

### ISSUE THREAD

**Issue by bobdoleknows** [flyingrub/scdl#200]
python3 scdl.py

Traceback (most recent call last):
File "scdl.py", line 59 in <module>
from scdl import __version__, CLIENT_ID, ALT_CLIENT_ID
file "/home/osboxes/.local/lib/python3.5/site-packages/scdl/scdl.py", line 59, 
in <module>
from scdl import __version__, CLIENT_ID, ALT_CLIENT_ID
ImportError: cannot import name '__version__'

**Comment by flyingrub** [comment]
`pip3 install scdl`

or

```
git clone https://github.com/flyingrub/scdl.git && cd scdl
python3 setup.py install
```
You cannot just run the python file.

Then you just have to type `scdl`
