### ISSUE TITLE
Print out stream url

### ISSUE THREAD

**Issue by parnold-x** [flyingrub/scdl#202]
youtube-dl has a option "-g, --get-url  | Simulate, quiet but print URL" which just prints out the stream url. Would great to also have this for scdl.

**Comment by flyingrub** [comment]
You can use youtube-dl with soundcloud 🎉.
`youtube-dl -g https://soundcloud.com/flyingrub/sets/industrial-techno-set`
I don't think this feature is necessary to scdl so closing this one.

**Comment by parnold-x** [comment]
Yeah found this too and forgot about the bug. Thx
