### ISSUE TITLE
-o doesn't skip tracks in playlist, starts off at track #1 instead of the assigned track number

### ISSUE THREAD

**Issue by DirkEdge** [flyingrub/scdl#203]
continuation from this: https://github.com/flyingrub/scdl/issues/201

attempting to download a playlist with an offset recognizes the syntax and number given, but doesn't start the download at the specified track.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/1f5e8b35e7615b8797d654742b8eaa20f41d73f0 fixes :)
