### ISSUE TITLE
Getting auth token (through https://dev.vm0.eu/scdl/) broken

### ISSUE THREAD

**Issue by SammyO** [flyingrub/scdl#209]
When trying to get my authentication token through https://dev.vm0.eu/scdl/, I get a "invalid_client: The client identifier provided is invalid." error (exact URL that is opened is `https://soundcloud.com/connect?client_id=a06b61f88c8297cc5abe6167a2d4c519&display=popup&redirect_uri=https%3A%2F%2Fdev.vm0.eu%2Fscdl%2Fcallback.html&response_type=code_and_token&scope=non-expiring&state=SoundCloud_Dialog_b0ba8`)

**Comment by flyingrub** [comment]
his client_id has been banned by soundcloud too.
