### ISSUE TITLE
Feature request: Download tracks that have been commented by user

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#210]
I'm not sure if Soundcloud's API would support such a thing...

But feature requesting to download tracks that have been commented by a certain user. I think it could be helpful to "filter out" good tracks and so forth.

**Comment by flyingrub** [comment]
I think that the liked track of an user already reflect good track choosen by an user. That's why I don't feel like this needs to be added to scdl. :/

**Comment by winterflags** [comment]
@flyingrub Some "influencer" accounts leave comments on tracks instead of liking them. I wouldn't ask for the feature if it didn't make sense, but if you don't want to include it then that's up to you.

**Comment by flyingrub** [comment]
Can you give some exemple of account that have this behaviour ?

**Comment by winterflags** [comment]
Here are some examples, they have their own Youtube-channels and do "influencer" aggregation via comments:

https://soundcloud.com/hurfyd
https://soundcloud.com/iazikza
https://soundcloud.com/tropicalbananas

**Comment by flyingrub** [comment]
I didn't know about this behaviour. Reopening !

**Comment by flyingrub** [comment]
fixed by #215
