### ISSUE TITLE
Prefix untaggable files with username

### ISSUE THREAD

**Issue by gs11** [flyingrub/scdl#212]
When downloading tracks and the original format is untaggable (e.g. wav, aif) the script informatively outputs a warning "This type of audio doesn't support tagging...".
Additionally, it'd be very useful to have the saved file name prefixed with the Soundcloud username to save information on who created/uploaded the track.

**Comment by flyingrub** [comment]
There is already an option for that the flag `--ad-to-file` add the username to a filename if it's not already in it. 👍

**Comment by gs11** [comment]
Didn't get that to work. Tried:
`scdl -l https://soundcloud.com/lukiss/gyrosaiff --addtofile`

Resulted in **gyros.aif**

**Comment by flyingrub** [comment]
you catched a bug that is now fixed 👍

**Comment by gs11** [comment]
Thanks!
