### ISSUE TITLE
Unable to download tracks using a, -t, -f, -p, -m or -c. Only able download individual tracks.

### ISSUE THREAD

**Issue by notvoid** [flyingrub/scdl#217]
Using Windows 10 Creators Update (automatically switched from using Command Prompt to PowerShell).

Tried on scdl version 1.6.4. I downloaded 1.6.7 from the pipy page but the program is still listed as 1.6.4 when typing in "scdl --version".

![issue](https://user-images.githubusercontent.com/4666808/29754917-1c4015b2-8b5d-11e7-9dac-92a2fc8d3de0.png)

Thanks in advance.

**Comment by flyingrub** [comment]
You are using an old scdl version. The issue is not related to scdl itself but the fact that you are using an outdated version. You can try to uninstall it (multiple times) and reinstall it.
