### ISSUE TITLE
Install does not work

### ISSUE THREAD

**Issue by Hennihenner** [flyingrub/scdl#218]
Sorry to bother you with this, but i simply cannot work out how to get this sucker to work. I have Python3.6 36 bit, Git and GitPython. Yet Git still claims that commands like pip and pip3 / pip3.6 and python/python3/... and respectively python doesn't allow Git to work - I'm completely dumbfounded. 

Where should i run the install command? I could only install the program using Git Bash, yet that doesn't get me any further. So which program should i actually use?

If it's possible, could you provide me with a barebones tutorial on how to get it to work from a fresh install, aka. what commands to run when i start python3.6/git bash to get scdl to work. I did manage to get the scdl directory, but can only move through directories on git bash, i'm a coding noob. 

Help is very much appreciated, thank you

**Comment by flyingrub** [comment]
are you using windows ?

**Comment by Hennihenner** [comment]
Yes

**Comment by flyingrub** [comment]
do you manage to run `python` in cmd ?

**Comment by Hennihenner** [comment]
i can run "Python" using the startmenu entry. entering python in cmd does not work

**Comment by hXtreme** [comment]
Have you restarted your computer after installing python? Sometimes update to PATH variable takes a restart.

If you have done so already then try reinstalling PYTHON with default settings.

**Comment by flyingrub** [comment]
I think we can close this as this issue is not related to scdl itself.
