### ISSUE TITLE
no place to donate

### ISSUE THREAD

**Issue by ob7** [flyingrub/scdl#221]
for a scdl that actually works!

**Comment by flyingrub** [comment]
The easiest way is to use my paypal email adress : `flyingrub@protonmail.com`

**Comment by ob7** [comment]
can I tip you in Denarius instead ?  It's a bitcoin clone.  Just download the wallet for your computer, and I can send you some Denarius valued at around 25 cents a piece right now.

**Comment by flyingrub** [comment]
There is no fees at all when donating from a person to another using paypal. But it's right that cryptocurrency are really interesting but why denarius instead of bitcoin or ethereum?

Aslo the current price is more 1DNR -> $0.00010744

**Comment by ob7** [comment]
Just because its a coin I have through mining.  I don't have any USD all I have is what I've been able to mine.  I could send you Ubiq instead of Denarius.  Ubiq is an Ethereum clone that has around 50 million market cap last time I checked.  Denarius only have 500k market cap so it could go up a lot.  You can trade Ubiq on bittrex.com which is a pretty legit exchange.  They are worth a little more than a dollar a piece right now.  https://coinmarketcap.com/currencies/ubiq/  ...  Just let me know if you get either one set up and I'll send over some coin.

**Comment by flyingrub** [comment]
let's try denarius `DNKWFjkjYSXeFjevDXzQzcNaKZNNkG1GyK`

**Comment by flyingrub** [comment]
Thank you very much !

**Comment by ob7** [comment]
Anytime!  I should have mentioned this already, but theres an older coin called denarius that's not the same one.  The coin I sent over is this one: https://coinmarketcap.com/currencies/denarius-dnr/

**Comment by ob7** [comment]
hey I can donate some more crypto because soundcloud ads are intruding ... I'll be using this alot more now.  I'm basically out of Denarius but I can send u some Ubiq if you give me your address.

**Comment by flyingrub** [comment]
Exchanged them for ETH some time ago. I now have 26.85$ :).

**Comment by ob7** [comment]
Yea price went up to $3 a piece last time I checked.  I sold all mine too :)  Glad it worked out.
