### ISSUE TITLE
Downloading stops with "Music already exists ! (exiting)" message

### ISSUE THREAD

**Issue by Supruim** [flyingrub/scdl#222]
The first time i started the code it worked flawlessly until i reached track number 487 with the message "Music already exists ! (exiting)"and it stopped downloading.

![schermafbeelding 2017-10-26 om 17 56 49](https://user-images.githubusercontent.com/33126914/32063356-3a2b1286-ba77-11e7-996b-4ef5dabea60f.png)

When i unliked one of the two different songs with the name "Repose" it continued downloading till 930 and beyond while typing this post.

I don't know how many people actually have this problem, but a few might.

Thank you @flyingrub for writing this great script!

**Comment by flyingrub** [comment]
This is intended actually and not a bug :)
You need to use the `-c` option to continue if a music already exists.
(I'm thinking of switching to continue by default as it often confuse the user)

**Comment by Supruim** [comment]
I feel so stupid now..
I thought i already read the Options but i missed that one.
Thank you for your helpful reply!

And i think that might not even be such a bad idea, or maybe a warning about identical track names.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/b1864369a3b7f0de1d87da603a8e1ffb0d8da34f should do it for now :)
