### ISSUE TITLE
Unable to -c after script encounters a song that has already been downloaded. 

### ISSUE THREAD

**Issue by maxbiddickk** [flyingrub/scdl#225]
`Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\Users\maxiv>scdl -l https://soundcloud.com/max-biddick -f
Soundcloud Downloader
Found a user profile
Retrieving all likes of user biddick,...
Retrieved 3044 likes
Likes n°1 of 3044
Downloading Sykotix & Aimeri - Tenderness
Music already exists ! (exiting)

C:\Users\maxiv>
C:\Users\maxiv>-c
'-c' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\maxiv>scdl -c
Usage:
    scdl -l <track_url> [-a | -f | -C | -t | -p][-c][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--onlymp3]
[--hide-progress][--min-size <size>][--max-size <size>]
    scdl me (-s | -a | -f | -t | -p | -m)[-c][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--onlymp3]
[--hide-progress][--min-size <size>][--max-size <size>]
    scdl -h | --help
    scdl --version

C:\Users\maxiv>scdl c
Usage:`

**Comment by flyingrub** [comment]
you need to add the -c option to your first command

**Comment by maxbiddickk** [comment]
Hi mate, bit of a command line noob here. How do I add -c option to first command?

**Comment by maxbiddickk** [comment]
Worked it out mate. Didn't realise that you just put one after the other. Cheers!
