### ISSUE TITLE
Token and authentication

### ISSUE THREAD

**Issue by Cepega-kef** [flyingrub/scdl#226]
Thank for project.
Tell me please, how (and where) to set token and others parameters to be able to use  key "-m". What does the "token" mean?I'm a noob)

**Comment by flyingrub** [comment]
As you can see here : https://docs.google.com/forms/d/e/1FAIpQLSfNxc82RJuzC0DnISat7n4H-G7IsPQIdaMpe202iiHZEoso9w/closedform
The application for new clientID is closed. So you will need to find one that already exists and provide a way to connect to your soundcloud account. Modipy for exemple : https://www.mopidy.com/authenticate/.

**Comment by flyingrub** [comment]
In fact I just noticed that you don't even need to replace our client_id by their.
