### ISSUE TITLE
ID3 tag for 'artist' uses SC username instead of artist name

### ISSUE THREAD

**Issue by justinTM** [flyingrub/scdl#239]
The ID3 tag uses `track['user']['username']` for the artist, but this is only accurate wehn the SoundCloud username is also the artist's name. Oftentimes the SoundCloud uploader is a 3rd party (eg. "3rdParty"), and the title of the track is the artist combined with the song title (eg. "Artist - Song"). This results in a file with the artist tag of "3rdParty" and a title tag of "Artist - Song".

Instead I propose a simple check, for example:
```
if track title contains '-':
    assign "Artist" to track['artist']
    assign "Song" to the track['title']
else:
    assign the SoundCloud username to track['artist']

assign track['artist'] to the artist ID3 tag
assign track ['title'] to the title ID3 tag
```

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/b59d3f425f11e6497db9937dce7648075faabafc
