### ISSUE TITLE
WAV/Original Files Aren't Named Correctly

### ISSUE THREAD

**Issue by Enverex** [flyingrub/scdl#244]
Downloading original files shows the correct information during download...

Downloading Some Music - Some Song
Downloading the original file.

But the actual downloaded file is named badly (or perhaps as it's named on the server itself) e.g. "SomeSong.wav" rather than "Some Music - Some Song.wav" as you'd expect.

There don't appear to be any existing options that would set the names to what I'd expect above.

**Comment by r00t-** [comment]
when downloading an original file, scdl will use the original filename of the upload, as provided by soundcloud:
https://github.com/flyingrub/scdl/blob/master/scdl/scdl.py#L460
which is ineed extremely confusing, as those names are unpredictable, and often useless. (like "final_render.wav")

**Comment by flyingrub** [comment]
I'm thinking that we could totally skip the original filename. It will simplify a lot this part of code and will make more sense most of the time. What do you guys think ?

**Comment by Enverex** [comment]
I agree. The worst part is people can't even see the original filename before it's downloaded so there are many cases where (if they're downloading more than 1 thing) you can end up having no idea which file is which (unless you go back through all the output from the terminal).

**Comment by r00t-** [comment]
simply removing the original-name handling would be a quick fix.

what i would find most useful would be a way to specify the naming scheme using some kind of format string.
that could then include the original upload name as an option.

for example, i have a very strong preference for keeping the original naming (the `permalink`) to be able to trace the downloaded file back to it's source.
(and modified my personal copy accordingly)

**Comment by r00t-** [comment]
we will still want to use the extension of the original name tho'

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/ea7fd439d373685cd332e672ccad8563a470ddd9
