### ISSUE TITLE
error title "character japanese"

### ISSUE THREAD

**Issue by hatokuro** [flyingrub/scdl#245]
When the title of a music contains Japanese characters, scdl displays an error.

"UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-12: ordinal not in range(128)"
link is "https://soundcloud.com/riverwave/riverwave-plastic-boat-original-mix"

**Comment by flyingrub** [comment]
Are you on windows ?

**Comment by hatokuro** [comment]
no, raspbian, raspberry pi 3

**Comment by gaddox** [comment]
See #257 for a quick-fix.

**Comment by flyingrub** [comment]
Duplicate https://github.com/flyingrub/scdl/issues/257
