### ISSUE TITLE
Readme showing features that don't exist yet

### ISSUE THREAD

**Issue by camjac251** [flyingrub/scdl#246]
I noticed that the readme to the tool shows 
--download-archive as an option but in the current version of the script, this is not available since the pull request for it was closed but the readme was updated to show the feature command.

**Comment by camjac251** [comment]
I was mistaken.

**Comment by flyingrub** [comment]
It's not yet on pypi if that was your concern

**Comment by camjac251** [comment]
The version numbers were the same on the github version and pypi. That's why I was confused
