### ISSUE TITLE
[BUG][1.6.11] curl: (3) <url> malformed

### ISSUE THREAD

**Issue by MyLive** [flyingrub/scdl#252]
I run "scdl -p /tmp -l https://soundcloud.com/oriuplift/uponly-207-no-talking"

 *---------------------------------------------------------------------------*
|               SoundcloudMusicDownloader           |   FlyinGrub rework      |
 *---------------------------------------------------------------------------*
[i] Using URL : https://soundcloud.com/oriuplift/uponly-207-no-talking
[i] Path where i will download music : /tmp
[i] I will exit if i found a file that already exist
[i] Detected download type : One single song
[i] Grabbing artists page
[-] Downloading ...
curl: (3) <url> malformed
[i] Setting tags finished!
[i] Downloading of .mp3 finished

**Comment by flyingrub** [comment]
You are still using the old bash scdl. Please remove it first.

**Comment by MyLive** [comment]
You´r right ... :-/ sorry for my stupidness
