### ISSUE TITLE
https://github.com/flyingrub/scdl/issues/109

### ISSUE THREAD

**Issue by wstafford3** [flyingrub/scdl#258]
This issue still exists with the latest version of assistant_library_demo.py on Raspbian  Stretch:
<<
HTTPError: 403 Client Error: Forbidden for url: https://embeddedassistant.googleapis.com/v1alpha2/projects/aiy-voice-project-205501/deviceModels/aiy-voice-project-205501-voice-kit
>>

This is preventing me from using the voice hat.

**Comment by flyingrub** [comment]
This is not related to scdl. Your script is using the request library that we also use.
