### ISSUE TITLE
Won't skip already downloaded files

### ISSUE THREAD

**Issue by Kaicastledine** [flyingrub/scdl#259]
Hello,

So I've tried with --download-archive and re-downloaded my playlists in hope that by creating the archive.I can re-run the scdl with the archive and it will update the playlists that I've already got downloaded.

However even when using --download-archive it gives me the error the file already exists, however if you run with -c it then re-downloads all the files again.

Whats the best way to just be able to re-run the tool and update/download songs that aren't already downloaded without re-doing the whole lot ?

**Comment by Kaicastledine** [comment]
Ah you have to use  --download-archive -c   not just one of them !

**Comment by Kaicastledine** [comment]
maybe edit/add wiki to include the -c or was it by design ?

**Comment by justinTM** [comment]
I actually wrote the --download-archive code, and the -c flag already existed in the script before I found it so I kept the functionality intact!  
  
If I remember correctly, there's a little blurb about `-c`, because playlists need it and likes needs it too

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/e833a22dd6676311b72fadd8a1c80f4a06acfad9
