### ISSUE TITLE
scdl doesn't detect songs

### ISSUE THREAD

**Issue by derhellelicht** [flyingrub/scdl#265]
Hey this is a very nice tool, but for
"scdl -l https://soundcloud.com/noisiaradio -a "

i get 

"
Found a user profile
Retrieving all tracks and reposts of user Noisia Radio...
Retrieved 0 tracks and reposts
Downloaded all 0 tracks and reposts of user Noisia Radio!
"

If i visit the page https://soundcloud.com/noisiaradio even without being logged in i can see and stream around 100 tracks :/

**Comment by flyingrub** [comment]
```Retrieved 183 tracks and reposts```
It works well here ?

**Comment by derhellelicht** [comment]
Yhea seems to work now. Strange :/
