### ISSUE TITLE
UnicodeEncodeError crashes scdl

### ISSUE THREAD

**Issue by tlhall** [flyingrub/scdl#266]
scdl crashes when I try to download this url:
    https://soundcloud.com/humanflourishingproject/episode-21-new-years-resolutions-for-2019

I'm using this hack in scdl.py version v1.6.12 for now:
```
431     filename = ''.join(c for c in filename if c not in invalid_chars)

- 432     try:                                                                      
- 433         print(filename)                                                      
- 434     except UnicodeEncodeError:                                                
- 435         filename="aFileNameThatWouldBreak_scdl.mp3"
                           
436     return filename
```
--

Log attached.

[scdlLog.txt](https://github.com/flyingrub/scdl/files/2741326/scdlLog.txt)

**Comment by flyingrub** [comment]
can you give an example log of this error without the fix ?

**Comment by tlhall** [comment]
I edited the original report attaching the log

**Comment by flyingrub** [comment]
On what system are you running ?

**Comment by tlhall** [comment]
I'm running 64-bit Cygwin on Windows 10.
Here's my locale:
LANG=C.UTF-8
LC_CTYPE="C"
LC_NUMERIC="C"
LC_TIME="C"
LC_COLLATE="C"
LC_MONETARY="C"
LC_MESSAGES="C"
LC_ALL=C

**Comment by tlhall** [comment]
I have a VM running CentOS Linux release 7.6.1810 and scdl works fine there with the same URL.
Let's close this and I'll just try to fix my Cygwin config.
