### ISSUE TITLE
How to generate a folder, and put the downloaded files in there?

### ISSUE THREAD

**Issue by CristenPerret** [flyingrub/scdl#273]
Hey I made a .bat to streamline your command-line. [Here](https://pastebin.com/k1zWbtUw)
I ran into a minor problem where I cannot utilize your  path argument with my directory because the slashes get doubled.
Its very minor, but maybe you might have an idea.
Its baseline command is "scdl -l %URL% --min-size "500k" --extract-artist --addtofile %Param% -c"
Where the variant parameters are -t / -f / -m.

Im bad at coding, but I know how to make batches a bit. Been having fun making this, so anything helps really. 
Let me explain it a bit more clear. Currently this batch will download the files to the directory that its located in. Im trying to have it just Generate a folder in that directory of the artists name preferably.
Really appreciate your effort in making this script, hopefully this project is still monitored so I can get some response!

**Comment by durgenheim** [comment]
hello,
tried your batch file, but it doesn't work for me, any hot tips on how to use it ?

cheers

**Comment by GiovanH** [comment]
Looks like you're running into windows batch escaping issues. This can be done trivially in bash using something like
```bash

while read USER; do
	mkdir ./users/${USER}/ -p
	scdl -l https://soundcloud.com/${USER}/ -t --path ./users/${USER}/
done < users.txt
```
