### ISSUE TITLE
adding option to skip track if alredy existing

### ISSUE THREAD

**Issue by Leone25** [flyingrub/scdl#274]
i was downloading the funky panda full libray from discord with my pretty bad connection and suddently it stopped on the 177th of 363, so i had to restart, the problem is thta it gives error if you try to download an alredy existing song. Would be nice if there were a comand to just skip the song if already exist, maybe -sk ?
tx if you do, i love this library, you saved me fro free websites full of ads
see you

**Comment by flyingrub** [comment]
` -c                          Continue if a downloaded file already exists`
As you can see on the help in the file or in the Readme :)

**Comment by Leone25** [comment]
well didn't see it because it was c small and not C big 😂 😅 , maybe change it? or have both? i think sk is better . . . but still thanks
