### ISSUE TITLE
scdl downloads empty file

### ISSUE THREAD

**Issue by useretail** [flyingrub/scdl#275]
scdl downloads empty file.
Steps to replicate:
`scdl --flac --addtofile -l http://soundcloud.com/liquid-manifest/1986a`

**Comment by JSinks** [comment]
Is this still the case for you @useretail ? I just attempted to run the command you have listed above and the download completed successfully, and a ~2MB file was downloaded

**Comment by flyingrub** [comment]
I cannot reproduce this error, I assume it is no longer relevant.
