### ISSUE TITLE
What can this that YouTube-DL can’t do?

### ISSUE THREAD

**Issue by github-userx** [flyingrub/scdl#276]

**Comment by flyingrub** [comment]
Both tool can do the same things, the main difference I think is more relative to the interface and option.
I use scdl to sync all my playlists. It is perfect for this job : it automatically use a subfolder for each playlist and also convert wave file when original file is available to flac, (flac support tag but wave don't and it save some space). I have a custom script that does the same with youtube-dl for my youtube playlist.
