### ISSUE TITLE
[feature request] Ability to write cover art to separate file.

### ISSUE THREAD

**Issue by BishopLX** [flyingrub/scdl#279]
Apologies if this isn't the right place for this but I would like to request the ability to write cover art separately to another file. I re-tag a lot of stuff for simplicity and would like to still have a cover art file of the original track since I usually end up overwriting it. This would make things faster. 

Something like this: 
```
scdl -l [url] --write-cover
```
Only issue I can see is that if you scrape an album with all the same cover art then you just end up a bunch of duplicates. It would still be easier than manually extracting the art from a playlist though if they were all different. I'd just delete duplicates.

**Comment by GL513** [comment]
I downloaded a playlist and all of the songs have the same cover art. Are you affected by this?

**Comment by BishopLX** [comment]
I don't know. I just stopped using SCDL it just broke later and it looked like this project was dead. I use other programs now.
