### ISSUE TITLE
Not downloading artwork

### ISSUE THREAD

**Issue by VozDeOuro** [flyingrub/scdl#288]
![image](https://user-images.githubusercontent.com/36045463/67911580-d8424080-fb65-11e9-8148-e97b8c06ea52.png)
command used
![image](https://user-images.githubusercontent.com/36045463/67911610-edb76a80-fb65-11e9-8d4d-2069e733f8c8.png)

**Comment by flyingrub** [comment]
![Screenshot from 2019-10-31 15-28-58](https://user-images.githubusercontent.com/3988628/67955877-88aa5600-fbf3-11e9-80d6-dd116d2e19e8.png)

**Comment by VozDeOuro** [comment]
i dont know why but i change the sysytem and try it again and din't work too.
first i downloaded in parrot os 
now i downloaded at WSL using UBUNTU and keep not downloading art work 
did you have any idea why
and its not the song too 
i downloaded a hole playlist and all files are without artwork
![image](https://user-images.githubusercontent.com/36045463/67972995-7a0d7000-fbee-11e9-96f1-e0c3969b294f.png)

**Comment by flyingrub** [comment]
![Screenshot from 2019-10-31 19-27-06](https://user-images.githubusercontent.com/3988628/67975498-8278a180-fc14-11e9-9006-459c75b5fc66.png)
