### ISSUE TITLE
scdl often only downloads 30 second previews of songs

### ISSUE THREAD

**Issue by TheT3ngu** [flyingrub/scdl#289]
Since a few days I have the issuse that scdl only downloads a preview of 30 to 32 seconds of some songs. The problem is hard to reproduce, since some artists work fine and scdl ist able to download full songs/playlists, and other playlists won't work and all scdl can fetch are previews (but full songs are playable via browser). Can there be something done about or is it a problem with SoundCloud?
Thanks in advance!

**Comment by flyingrub** [comment]
Could you give example url that trigger this behaviour ?

**Comment by telarmago** [comment]
I have noticed this too, here are some songs that it has happened twice for me with:

https://soundcloud.com/lootemusic/85-feat-gnash
https://soundcloud.com/deanlewisofficial/be-alright
https://soundcloud.com/halseymusic/without-me

The output looks like
```
Downloading 85% (feat. gnash)
[################################] 468/468 - 00:00:00
Setting tags...
85% (feat. gnash).mp3 Downloaded.
```

**Comment by xcession** [comment]
This also happened to me too. Not every songs btw.

**Comment by wilzh40** [comment]
+1 This is happening with the last couple artists that I tried

**Comment by iVegas** [comment]
I use `--min-size 1m` to detect such of tracks.
Here the examples
```
scdl -c --min-size 1m -l https://soundcloud.com/dukeandjones/waist-down-out-now
scdl -c --min-size 1m -l https://soundcloud.com/gentlemensclubuk/gentlemens-club-faded
```
both track are not a preview tracks

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/30968bc5a19703fcf3332613f96e497e43bd6771 introduce a fix for this and the issue with unauthorized track since yesterday.
For now there is no progress bar and we need ffmpeg to decode HLS stream.

**Comment by flyingrub** [comment]
I am closing this now since this should be fixed by all the commit since then.
