### ISSUE TITLE
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url:

### ISSUE THREAD

**Issue by tlhall** [flyingrub/scdl#290]
This was working a few weeks ago so I think something has changed on soundcloud.com

[scdlbug.txt](https://github.com/flyingrub/scdl/files/3899137/scdlbug.txt)

**Comment by K3nni** [comment]
Same on Debian GNU/Linux 9 (stretch) 

[debugscdl.txt](https://github.com/flyingrub/scdl/files/3900888/debugscdl.txt)

**Comment by flyingrub** [comment]
Checkout master and this comment : https://github.com/flyingrub/scdl/issues/289#issuecomment-559146519

**Comment by hentaiwithsenpai** [comment]
> Checkout master and this comment : [#289 (comment)](https://github.com/flyingrub/scdl/issues/289#issuecomment-559146519)

Still receiving this issue after updating.

**Comment by flyingrub** [comment]
`sudo pip3 uninstall scdl` run this two times and reinstall from git

**Comment by hentaiwithsenpai** [comment]
> `sudo pip3 uninstall scdl` run this two times and reinstall from git

That got me further. But, now i'm getting.

"Soundcloud Downloader
Found a track
Retrieving more info on the track
Downloading First Original Song (snippet)- Prod. Cosmo
'ffmpeg' is not recognized as an internal or external command,
operable program or batch file.
'Signature' is not recognized as an internal or external command,
operable program or batch file.
'Key-Pair-Id' is not recognized as an internal or external command,
operable program or batch file.
Setting tags...
Error trying to set the tags...
Cannot update utime of file"

edit: Installed FFMPEG
now getting this still.

"'https://cf-hls-media.sndcdn.com/playlist/2Pdhd7ZdBUqG.128.mp3/playlist.m3u8?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLWhscy1tZWRpYS5zbmRjZG4uY29tL3BsYXlsaXN0LzJQZGhkN1pkQlVxRy4xMjgubXAzL3BsYXlsaXN0Lm0zdTgiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE1NzQ5NTQzOTZ9fX1dfQ__: No such file or directory
'Signature' is not recognized as an internal or external command,
operable program or batch file.
'Key-Pair-Id' is not recognized as an internal or external command,
operable program or batch file.
Setting tags...
Error trying to set the tags...
Cannot update utime of file"

**Comment by flyingrub** [comment]
I did not test this on windows still... I will try to fix this later.

**Comment by hentaiwithsenpai** [comment]
> I did not test this on windows still... I will try to fix this later.

Thanks brother :)

**Comment by jimmynames** [comment]
yo big up for this @flyingrub legend

**Comment by tlhall** [comment]
I got a client_id with: https://mopidy.com/authenticate and poked it into .../site-packages/scdl/__init__.py so this issue is fixed for me.
