### ISSUE TITLE
Got numerous "Error trying to set the tags" messages, can't find mp3 download, only download sems to be a m3u file

### ISSUE THREAD

**Issue by grn-century** [flyingrub/scdl#293]
My OS is Linux Mint 19.2 Cinnamon version 4.2.4

Here is the output when I tried to download an album from soundcloud: 

>scdl -l https://soundcloud.com/swansofficial/sets/not-here-not-now-1
Soundcloud Downloader
Found a playlist
Track n°1
Retrieving more info on the track
Downloading To Be Kind
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
To Be Kind.mp3 Downloaded.
Track n°2
Retrieving more info on the track
Downloading Just A Little Boy
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
Just A Little Boy.mp3 Downloaded.
Track n°3
Retrieving more info on the track
Downloading Coward
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
Coward.mp3 Downloaded.
Track n°4
Retrieving more info on the track
Downloading She Loves Us!
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
She Loves Us!.mp3 Downloaded.
Track n°5
Retrieving more info on the track
Downloading Oxygen…
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
Oxygen….mp3 Downloaded.
Track n°6
Retrieving more info on the track
Downloading The Seer / Bring the Sun / Toussaint L'ouverture
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
The Seer  Bring the Sun  Toussaint L'ouverture.mp3 Downloaded.
Track n°7
Retrieving more info on the track
Downloading Nathalie Neal
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
Nathalie Neal.mp3 Downloaded.
Track n°8
Retrieving more info on the track
Downloading Kirstin Supine (Demo)
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
Kirstin Supine (Demo).mp3 Downloaded.
Track n°9
Retrieving more info on the track
Downloading Screen Shot (Demo)
sh: 1: ffmpeg: not found
Setting tags...
Error trying to set the tags...
Cannot update utime of file
Screen Shot (Demo).mp3 Downloaded.

I can't find the mp3 files, only a file called Not Here Not Now/Not Here Not Now.m3u in my home directory. It does not seem to sent the files to the output directory I tried to set up in the config file, which is /home/USER/Music

**Comment by flyingrub** [comment]
` sh: 1: ffmpeg: not found` as you can see here you need ffmpeg for this to work.

**Comment by grn-century** [comment]
thank you, all seems to be working great now
