### ISSUE TITLE
You can use `soundcloud-likes` if `scdl` isn't working for you

### ISSUE THREAD

**Issue by codiflow** [flyingrub/scdl#300]
As scdl didn't work for me I just tried another script called `soundcloud-likes` (https://github.com/drivelous/soundcloud-likes) and got it working.

Here you can read what I did to get it running:  #https://github.com/drivelous/soundcloud-likes/issues/3#issuecomment-573339836 @

**Comment by flyingrub** [comment]
You can use the same technique for scdl if you use the version on pipy, the version before the HLS commit. https://github.com/flyingrub/scdl/commit/1e9ef0b048dbae84ba7a9ad7e9db14304526ed26
