### ISSUE TITLE
Provide clear installation instructions 

### ISSUE THREAD

**Issue by UkwaA** [flyingrub/scdl#309]
Hey, running 'brew install ffmpeg' and fixing permissions for that instant to run properly finally fixed everything, but I don't think others with the same issue will be aware of this fix. Could you add something regarding installing ffmpeg for this to properly work (at least on Mac) to the ReadMe so other people can also understand how to use it?

**Comment by flyingrub** [comment]
I think this issue still makes sense, we need to provide clear installation instructions for every os.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/wiki/Installation-Instruction
I did start this wiki page.
