### ISSUE TITLE
401 Client Error: Unauthorized for url

### ISSUE THREAD

**Issue by codydbgt** [flyingrub/scdl#310]
401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/655160579/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Traceback (most recent call last):
  File "/home/ntg/.local/lib/python3.6/site-packages/scdl/scdl.py", line 357, in download
    download_track(item)
  File "/home/ntg/.local/lib/python3.6/site-packages/scdl/scdl.py", line 496, in download_track
    r.raise_for_status()
  File "/home/ntg/.local/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/655160579/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z

**Comment by codydbgt** [comment]
i did follow this it did not work https://github.com/flyingrub/scdl/issues/292

**Comment by flyingrub** [comment]
Are you sure you are using the latest version ?
Can you provide some song that fails ?

**Comment by HeadbangGang** [comment]
I am also having this error. When downloading only the likes from an account (Which has 649 Likes) I only downloaded 37 songs. Another issue is for some reason SCDL is only seeing 571 likes? Below is an example of the output with an example song...Thanks for the help!

Tracks and reposts n°245 of 571
Found a track
Downloading [BC030] Space Race - Riot (Squelch Remix)
401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/274708726/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 348, in download
    parse_url(uri)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 262, in parse_url
    download_track(item)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/scdl/scdl.py", line 496, in download_track
    r.raise_for_status()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api.soundcloud.com/tracks/274708726/stream?client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z

**Comment by codydbgt** [comment]
yes im downloding 2700 of my likes many that are long 10min+ will not dl

**Comment by datesss** [comment]
> yes im downloding 2700 of my likes many that are long 10min+ will not dl and i used the instrusctions to install form git so that should be the latest yes?
> 
> ```
> pip uninstall scdl
> pip install git+https://github.com/flyingrub/scdl
> ```

This worked for me, thanks!

**Comment by TheOnlyMunk** [comment]
> yes im downloding 2700 of my likes many that are long 10min+ will not dl and i used the instrusctions to install form git so that should be the latest yes?
> 
> ```
> pip uninstall scdl
> pip install git+https://github.com/flyingrub/scdl
> ```

also worked here!

**Comment by OblackatO** [comment]
> yes im downloding 2700 of my likes many that are long 10min+ will not dl and i used the instrusctions to install form git so that should be the latest yes?
> 
> ```
> pip uninstall scdl
> pip install git+https://github.com/flyingrub/scdl
> ```

Worked for me as well !
