### ISSUE TITLE
Error Running Sample Code

### ISSUE THREAD

**Issue by zayoob** [flyingrub/scdl#324]
Hi,

Running into a very frustrating problem here. I am trying to run one of the example snippets "scdl -l https://soundcloud.com/jumpstreetpsy/low-extender" in shell, but my response is a carrot under the first character of the URL and an "invalid syntax" error.

Does anyone know what this could be?

**Comment by flamesies** [comment]
Hi zayoob,

I've tried running
`scdl -l https://soundcloud.com/jumpstreetpsy/low-extender`
And I don't get a Syntax error. 
What version are you running?
`scdl --version`

**Comment by zayoob** [comment]
i get "name 'version' is not defined"

**Comment by zayoob** [comment]
that seems like something with my install yeah?

**Comment by zayoob** [comment]
found it in the files scdl==1.6.12

**Comment by flyingrub** [comment]
`python -m scdl -l yoururl`
You are probably on windows and something is wrong with your python install.

**Comment by flyingrub** [comment]
`python -m scdl -l yoururl`
You are probably on windows and something is wrong with your python install.
