### ISSUE TITLE
Possibility to rename the file with a command line argument.

### ISSUE THREAD

**Issue by MyAlien** [flyingrub/scdl#325]
Hello,

Do you have the possibility to rename the file .mp3 with a command line argument.

E.g : scdl -l https://soundcloud.com/music/url-track ( -OutputFileName ) OtherName.mp3

Thank you very much for your help.

**Comment by 7x11x13** [comment]
This can be done with the `--name-format` option.
e.g. `scdl -l https://soundcloud.com/music/url-track --name-format OtherName.mp3`
