### ISSUE TITLE
Soundcloud Downloader Failed to get item...

### ISSUE THREAD

**Issue by kapena** [flyingrub/scdl#326]
No longer able to download w SCDL. Keep getting this message saying failed to get item.. 

Running current version of SCDL. Soundclound must of changed their api? 

`~ scdl -l https://soundcloud.com/user-20200202/if-future-dreaming-is-real-this-is-an-example-of-it
Soundcloud Downloader
Failed to get item...`

**Comment by GiovanH** [comment]
Same issue here

**Comment by flyingrub** [comment]
Run `pip3 uninstall scdl` and reinstall.

**Comment by rafaelrs** [comment]
I did it, but still getting same:
`~ pip3 uninstall scdl
Uninstalling scdl-1.6.12:
  Would remove:
    /home/rafaelrs/.local/bin/scdl
    /home/rafaelrs/.local/lib/python3.7/site-packages/scdl-1.6.12-py3.7.egg-info
    /home/rafaelrs/.local/lib/python3.7/site-packages/scdl/*
Proceed (y/n)? y
  Successfully uninstalled scdl-1.6.12

~ pip3 install scdl --user
Collecting scdl
  Using cached https://files.pythonhosted.org/packages/2f/8f/a0704141f3157c70038da387ed3cf1d923eab158e60fa46fbd5c4c4c27a1/scdl-1.6.12.tar.gz
Requirement already satisfied: docopt in /home/rafaelrs/.local/lib/python3.7/site-packages (from scdl) (0.6.2)
Requirement already satisfied: mutagen in /home/rafaelrs/.local/lib/python3.7/site-packages (from scdl) (1.42.0)
Requirement already satisfied: termcolor in /home/rafaelrs/.local/lib/python3.7/site-packages (from scdl) (1.1.0)
Requirement already satisfied: requests in /usr/lib/python3.7/site-packages (from scdl) (2.22.0)
Requirement already satisfied: clint in /home/rafaelrs/.local/lib/python3.7/site-packages (from scdl) (0.5.1)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/lib/python3.7/site-packages (from requests->scdl) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/lib/python3.7/site-packages (from requests->scdl) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/lib/python3.7/site-packages (from requests->scdl) (1.25.7)
Requirement already satisfied: args in /home/rafaelrs/.local/lib/python3.7/site-packages (from clint->scdl) (0.1.0)
Installing collected packages: scdl
  Running setup.py install for scdl ... done
Successfully installed scdl-1.6.12

~ scdl -l https://soundcloud.com/james-everingham -a
Soundcloud Downloader
Failed to get item...
`

**Comment by flyingrub** [comment]
Look here to properly install scdl, the pip repo is outdated : https://github.com/flyingrub/scdl/wiki/Installation-Instruction

**Comment by rafaelrs** [comment]
Thanks, that worked

**Comment by vivatequila** [comment]
> Look here to properly install scdl, the pip repo is outdated : https://github.com/flyingrub/scdl/wiki/Installation-Instruction

I'm getting this problem:

C:\scdl> python3 -m scdl.scdl https://soundcloud.com/mrbillstunes/65-copycatt
Usage:
    scdl -l <track_url> [-a | -f | -C | -t | -p][-c][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--addtimestamp]
[--onlymp3][--hide-progress][--min-size <size>][--max-size <size>][--remove]
[--no-playlist-folder][--download-archive <file>][--extract-artist][--flac]
    scdl me (-s | -a | -f | -t | -p | -m)[-c][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--addtimestamp]
[--onlymp3][--hide-progress][--min-size <size>][--max-size <size>][--remove]
[--no-playlist-folder][--download-archive <file>][--extract-artist][--flac]
    scdl -h | --help
    scdl --version
PS C:\scdl> python3 -m scdl.scdl -l https://soundcloud.com/mrbillstunes/65-copycatt
Soundcloud Downloader
Failed to get item...
PS C:\scdl>
