### ISSUE TITLE
The System cannot find the specified file.

### ISSUE THREAD

**Issue by shurjeelfayyaz** [flyingrub/scdl#327]
Some of my songs are downloaded but 70% of them ends with this error. Can you help me? I am using python for the first time?

**Comment by flyingrub** [comment]
Without any log of the output I cannot help you ...
You are probably using an outdated version. 
Run `pip3 uninstall scdl` then follow the instruction here :
https://github.com/flyingrub/scdl/wiki/Installation-Instruction
