### ISSUE TITLE
[REQUEST] write cover art url as cover comment meta data

### ISSUE THREAD

**Issue by youkknowho** [flyingrub/scdl#328]
![image](https://user-images.githubusercontent.com/45168911/80224946-028c3b00-867d-11ea-9bb7-8ee5edbc0412.png)

(Tagging app I use is TagScanner)

**Comment by flyingrub** [comment]
What is the benefit of duplicating it ?

**Comment by youkknowho** [comment]
The artwork URL doesn't change. It's handy just incase I need to grab the original art (replace "t500x500" with "original"), the link will be there.
 **(This is all for archival purposes)**

You don't need to implement it but maybe if you can help me add this to it myself?

**Comment by youkknowho** [comment]
@flyingrub hi, I've added it myself
LINE: 735 
                    desc=track['artwork_url'], data=out_file.read()
