### ISSUE TITLE
Name output file manually

### ISSUE THREAD

**Issue by travs** [flyingrub/scdl#33]
Something like `scdl -l <track_url> -O myFilename.mp3` would be convenient. We can't use `-of` I guess, because `-o` and `-f` are already in use and it would be confusing.

Currently I use **scdl** in a script, and it would be much easier to do stuff with the downloaded file if I knew what the output filename was going to be.

**Comment by flyingrub** [comment]
this mean that every songs downloaded will have the same filename...
your script can use the scdl stdout output to check the filename.
exemple:
```
fly@Minotoor ~ $ scdl -l https://soundcloud.com/phanton/phanton-derpinas-short-video
Soundcloud Downloader
Downloading to /home/fly...

Found a track
Downloading Phanton - Derpinas (Short Video Edit)
100% [......................................................] 3719835 / 3719835
Settings tags...

Phanton - Derpinas (Short Video Edit).mp3 Downloaded.
``` 
 `Phanton - Derpinas (Short Video Edit).mp3` is the filename

**Comment by flyingrub** [comment]
just something : why don't you just check for track in your folder and then use them in your script ?

**Comment by travs** [comment]
You mean wait for a file to be created then act on it? I do not know how to do that in bash, but I will look into it.

**Comment by flyingrub** [comment]
```
for f in *.pdf
do
	#do something with the filename $f.
done
```
