### ISSUE TITLE
Cannot longer download m4a file 

### ISSUE THREAD

**Issue by kdn9101999** [flyingrub/scdl#336]
I haven't been using scdl for some time but I need to use it again now. However, the program only downloads 128kbps files using the scdl -l command nowadays, in the past I was able to download m4a 256kbps files, tried with those songs and it still didn't work. 
What should I do now?

**Comment by flyingrub** [comment]
I don't think we were able to download m4a ever. At least soundcloud never provided those to my knowledge.

**Comment by blackjack4494** [comment]
youtube-dl can do it if you provide authorization headers. However I modified the extractor to make it work out of box.

If you want to reuse login ability to be able to download aac hq (m4a) you can use my [sample code](https://gist.github.com/blackjack4494/c67adb54aaf2db79f394279fc9d76bb6)
As far as I know you still need a paid account to get higher quality.
Credits appreciate if you gonna use the code :)
@flyingrub
