### ISSUE TITLE
after i successfully installed scdl on windows but script won't work.

### ISSUE THREAD

**Issue by sunyoid** [flyingrub/scdl#339]
After i download scdl and created a new dir on my C drive, i typed in scdl -l [trackname] into the command prompt and i keep getting this error, "scdl is not recognized an internal or external command..." is there any way i can get this thing to work?

**Comment by AdrianoCahete** [comment]
You need to add the Python lib and bin to Windows PATH. After that you do a `refreshenv` command or close and open the command line again.

More info [here](https://stackoverflow.com/a/4855685/1032384)

**Comment by flyingrub** [comment]
Issue not relate to scdl itself so closing this one.
