### ISSUE TITLE
Program should refuse to run with an informative error message if ffmpeg is not found in PATH

### ISSUE THREAD

**Issue by michelfaria** [flyingrub/scdl#349]
Currently, the program tries to download all songs and displays a non-descriptive error for each song if it cannot find ffmpeg.
Ideally the program should fail early and refuse to download any songs if it doesn't find ffmpeg in the PATH.

**Comment by michelfaria** [comment]
#350 I made a pull request for this

**Comment by flyingrub** [comment]
Thanks for the PR, it has been merged :)
