### ISSUE TITLE
AttributeError: 'ResourceList' object has no attribute 'kind'

### ISSUE THREAD

**Issue by syphoxy** [flyingrub/scdl#35]
command executed: `python3 /usr/bin/scdl -l "https://soundcloud.com/syphoxy/likes"`
command output:
```
Traceback (most recent call last):
  File "/usr/bin/scdl", line 9, in <module>
    load_entry_point('scdl==v1.0.6', 'console_scripts', 'scdl')()
  File "/usr/lib/python3.3/site-packages/scdl/scdl.py", line 87, in main
    parse_url(arguments["-l"])
  File "/usr/lib/python3.3/site-packages/scdl/scdl.py", line 146, in parse_url
    elif item.kind == 'track':
AttributeError: 'ResourceList' object has no attribute 'kind'
```

I just installed today via `sudo python3-pip install scdl` so it should be most up to date. not sure how to resolve this issue.

I'm not sure what the relevant information is to troubleshoot this issue. feel free to bug me about my system installation. for reference, it is Fedora 20.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/fa4a9c612d6388e04ca2f491998e4e409f706eb0
