### ISSUE TITLE
May I please get beginner-friendly instructions?

### ISSUE THREAD

**Issue by shantanub08** [flyingrub/scdl#351]
This post was first a question as to how to use scdl without knowing much about python. But by just using common sense, I found out exactly what needed to be done all by myself. So hopefully this post can help those absolute noobs like myself to get scdl running on Windows 10

1. Install [python](https://www.python.org/ftp/python/3.8.5/python-3.8.5.exe) (make sure you let it add path to environment variables. You can do this manually as well in case you ignore it during installation)
2. Install [ffmpeg](https://www.gyan.dev/ffmpeg/builds/ffmpeg-release-full.zip) and add do the path thing to this as well
3. Then download this repo.
4. Open cmd and locate to the downloaded repo directory.
5. Type `python setup.py install`

From here, just type `scdl` and you'll get everything else you need to know on cmd itself. This may not be the absolute beginner-friendly post but with basic windows and coding experience, I believe this is noob friendly enough.

**Comment by rudeboi1992** [comment]
@shantanub08 Brilliant, thank you so MUCH!!!!
