### ISSUE TITLE
Not getting album art embedded in songs

### ISSUE THREAD

**Issue by shantanub08** [flyingrub/scdl#352]
[This was asked before also in 2015](https://github.com/flyingrub/scdl/issues/64) but I guess it used to work then because my downloaded songs don't come with the respective album art. Also, how do I set "unknown" albums to "SoundCloud"?

And yes, I tried downloading an album which did tag the album-name correctly but the album art is nowhere to be found.

**Comment by flyingrub** [comment]
By default we do not put the Album tag to soundcloud anymore, since this was preventing to display the correct album art on some players.
The album art is supposed to be embedded in the mp3 file, you should be able to see for example with VLC.
