### ISSUE TITLE
git

### ISSUE THREAD

**Issue by gimmeAll** [flyingrub/scdl#354]
There are no issues with the software, I am just here to hopefully have a question answered. I keep having this error when I attempt installing the repo "ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?" and I know its because I dont know how to get the git command installed. Can anyone tell me how to get the git command installed or where to find it?

**Comment by vgzhn** [comment]
https://git-scm.com/download/win

**Comment by TheTechRobo** [comment]
If you're not on Windows, install it using your favourite package manager (Debian (includes Ubuntu): `sudo apt-get install git`)

**Comment by flyingrub** [comment]
I am closing this as it is not related to scdl itself
