### ISSUE TITLE
Feature Request: Allow a download path to be set for all future downloads

### ISSUE THREAD

**Issue by UkwaA** [flyingrub/scdl#357]
Something I've been wishing this app came with for a while. I used to be able to change the code to do it myself but after some change in the past I can't do it anymore.

**Comment by jz1** [comment]
should work fine with the path parameter
    --path [path]               Use a custom path for downloaded files

**Comment by UkwaA** [comment]
> should work fine with the path parameter
> --path [path] Use a custom path for downloaded files

It can't be used by itself though. It's exhausting having to type out the custom path at the end of every command.

**Comment by jz1** [comment]
Did you try changing the path in the cfg file which is standard as . (current path)? 
Think that path is to set the standard download folder

**Comment by gpchelkin** [comment]
Let me clarify a bit :)
@UkwaA you can create configuration file for scdl: `$HOME/.config/scdl/scdl.cfg`
And edit it to something like:
```
[scdl]
path = /path/to/your/download/dir
```

(reference: https://github.com/flyingrub/scdl/blob/master/config/scdl.cfg)
So then default download path will always be `/path/to/your/download/dir`

**Comment by UkwaA** [comment]
> Let me clarify a bit :)
> @UkwaA you can create configuration file for scdl: `$HOME/.config/scdl/scdl.cfg`
> And edit it to something like:
> 
> ```
> [scdl]
> path = /path/to/your/download/dir
> ```
> 
> (reference: https://github.com/flyingrub/scdl/blob/master/config/scdl.cfg)
> So then default download path will always be `/path/to/your/download/dir`

and this solved it. thanks!
