### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:

### ISSUE THREAD

**Issue by winterflags** [flyingrub/scdl#359]
Getting this error with `scdl==1.6.12`, using `Python 3.9.1`.

When running:

`scdl -l https://soundcloud.com/my_username -f -c --addtofile --path /my/path`

I get:

```
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-v2.soundcloud.com/users/XXXXXXXX/track_likes?limit=200&client_id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&linked_partitioning=1&oauth_token=X-XXXXXX-XXXXXXXX-XXXXXXXXXXXXXX
```

I have updated to the latest version of scdl:

`pip3 install git+https://github.com/flyingrub/scdl --upgrade`

**Comment by flyingrub** [comment]
You will need to uninstall all previous installations first.
`pip3 uninstall scdl`. Run it twice.

**Comment by winterflags** [comment]
> You will need to uninstall all previous installations first.
> `pip3 uninstall scdl`. Run it twice.

Thanks. Do you mean that I should run uninstall twice?

The second time I get:
```
WARNING: Skipping scdl as it is not installed.
```

I tried installing it again using `pip3 install git+https://github.com/flyingrub/scdl`, but it did not help with the issue.

**Comment by Sciguy429** [comment]
Getting the same issue myself on the latest version. Reinstalling did not fix anything either.

**Comment by flyingrub** [comment]
@winterflags yeah I meant run it twice just to be sure sometimes you can have separate version installed at different place on your system.
Try to uninstall again and run `which scdl`.

**Comment by winterflags** [comment]
> @winterflags yeah I meant run it twice just to be sure sometimes you can have separate version installed at different place on your system.
> Try to uninstall again and run `which scdl`.

```
  Successfully uninstalled scdl-1.6.12
$ which scdl
scdl not found
```

Then when reinstalling again, still getting the same problems. Any ideas on what can be wrong?

**Comment by jz1** [comment]
I assume the XXXXX in your log is hiding the details.
What output do you get if you put the original link of the log in the browser?

**Comment by winterflags** [comment]
> I assume the XXXXX in your log is hiding the details.

Yes. I don't know exactly which details pertain to my personal ID on Soundcloud.

> What output do you get if you put the original link of the log in the browser?

I interpret this that I should visit the "Forbidden URL" in my browser. A blank page with the text `{}` comes up – seems to imply an empty data structure?

**Comment by winterflags** [comment]
> > > I assume the XXXXX in your log is hiding the details.
> > 
> > 
> > Yes. I don't know exactly which details pertain to my personal ID on Soundcloud, but could "uncensor" the URL if I knew.
> > > What output do you get if you put the original link of the log in the browser?
> > 
> > 
> > I interpret this that I should visit the "Forbidden URL" in my browser. A blank page with the text `{}` comes up – seems to imply an empty data structure?
> 
> paste the link without the oauth token, thats basically your personal token, client_id is already in the script and users id is just the id of the user. You should still see data when you paste it in the browser and not just {}.
> what do you get if you visit in browser without the &oauth_token=X-XXXXXX-XXXXXXXX-XXXXXXXXXXXXXX

Thanks. When visiting the URL without the oauth_token part, I can see all the data starting with `{"collection"`...

**Comment by jz1** [comment]
Then most like you didnt save right or retrieved the right oauth token

**Comment by winterflags** [comment]
> Then most like you didnt save right or retrieved the right oauth token

Sorry, but am I really using a token for this command? Again, the command used is:

`scdl -l https://soundcloud.com/username -f -c --addtofile --path /my/path`

I can see in the readme that `-s` and `me` seems to use a token, but I've not used this in a long time. The above command worked fine just a couple of weeks ago, and I haven't changed the exact string.

**Comment by flyingrub** [comment]
Remove your token from the config, it might be expired or something. That should be the cause since it is the only difference there is and it is working well here.

**Comment by winterflags** [comment]
> Remove your token from the config, it might be expired or something. That should be the cause since it is the only difference there is and it is working well here.

Thanks, that worked. Removed my token from `~/.config/scdl/scdl.cfg` by setting it to `auth_token = `.
