### ISSUE TITLE
ImportError: No module named configparser ???

### ISSUE THREAD

**Issue by glowinthedarkninja** [flyingrub/scdl#360]
I'm pretty stupid when it comes to GitHub

Traceback (most recent call last):
  File "C:\Python27\Scripts\scdl-script.py", line 11, in <module>
    load_entry_point('scdl==1.6.12', 'console_scripts', 'scdl')()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2443, in load
    return self.resolve()
  File "c:\python27\lib\site-packages\pkg_resources\__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\python27\lib\site-packages\scdl\scdl.py", line 68, in <module>
    import configparser
ImportError: No module named configparser

I'm unsure of what to do here, but I am pretty sure it's not working.

**Comment by flyingrub** [comment]
You are using python 2.7, this only works on python 3.

**Comment by glowinthedarkninja** [comment]
Oof that's embarrassing. I installed python 3 from their online source and from the microsoft store.

I just now tried uninstalling Python2.7 and running through the installation instructions again. 
Now when I try to run scdl -l "url" -f, cmd returns:

'scdl' is not recognized as an internal or external command,
operable program or batch file.

after browsing I ran: 
python3 -m scdl.scdl
and it returned:
C:\>python3 -m scdl.scdl
Usage:
    scdl -l <track_url> [-a | -f | -C | -t | -p][-c | --force-metadata][-n <maxtracks>][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--addtimestamp]
[--onlymp3][--hide-progress][--min-size <size>][--max-size <size>][--remove][--no-album-tag]
[--no-playlist-folder][--download-archive <file>][--extract-artist][--flac]
    scdl me (-s | -a | -f | -t | -p | -m)[-c | --force-metadata][-n <maxtracks>][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--addtimestamp]
[--onlymp3][--hide-progress][--min-size <size>][--max-size <size>][--remove]
[--no-playlist-folder][--download-archive <file>][--extract-artist][--flac][--no-album-tag]
    scdl -h | --help
    scdl --version

I then found User vgzhn's post in issue #271 and ran:
python3 -m scdl.scdl -l "url" -f
and was sucessful

*note "url" is the profile URL im trying to download from.
