### ISSUE TITLE
FEATURE | For urls from mobile app

### ISSUE THREAD

**Issue by AP-Atul** [flyingrub/scdl#370]
So for mobile app the url is like this
```https://soundcloud.app.goo.gl/pHSQd```
which does not resolve as it redirects.

so something like this helps
```python
url = "https://soundcloud.app.goo.gl/pHSQd"
url = requests.get(url).url.split("?")[0]
```

BTW, I was making a small app on local network to download from app so this issue came up

**Comment by 7x11x13** [comment]
Added support for mobile app links in version 2.3.0
