### ISSUE TITLE
Add support for m.soundcloud.com links

### ISSUE THREAD

**Issue by m040601** [flyingrub/scdl#373]
Thanks for your work in this very interesting tool.

A very simple request.

I'm using ArchLinux, and as a heavy terminal and command line user, I
am also browsing the internet with a text browser.

In my case it's w3m. Highly recommended.

These text browser dont support javascript of course.
Using them on soundcloud.com, you get a message like "Not supported", "Upgrade your browser" etc.

But, believe it or not, you can perfectly use the soundclound service, if you still go to
m.soundclound.com with a text browser. No javascript needed. Just like with other Android browsers. You can browse and see everything, and use an old computer for example. Very efificient. You cant of course listen in the browser. But thats what scdl is for. This combination is extremely interesting and can be used for automation and scripting.

Anyway.

So when I copy a link, from my browser to download with scdl, the link is
https://m.soundcloud.com/someuser/sometrack. But, scdl is expecting "https://sound..." , not "https://m.sound" . So it fails to parse it.

Example:

 ```
   $ scdl -l https://m.soundcloud.com/thekidlaroi/stay
Soundcloud Downloader
Error resolving url, retrying...
Failed to get item...

```

This of course is not a big problem, I just remove the "m." and it works:

```
    $ scdl -l https://soundcloud.com/thekidlaroi/stay
Soundcloud Downloader
Found a track
Downloading Stay (with Justin Bieber)
Setting tags...
Stay (with Justin Bieber).mp3 Downloaded.

```

This a minor annoyance, but I believe should be a quick and easy code update.
It would make things so much more confortable and eficient for command line users..

Thanks in advance.

**Comment by 7x11x13** [comment]
Added support for mobile links in version 2.3.0
