### ISSUE TITLE
Force download of streamed track

### ISSUE THREAD

**Issue by travs** [flyingrub/scdl#38]
Sometimes I may want to download the streamed version of the track rather than the original file, even if original file is available.

Maybe the original file is a WAV and I want to have an MP3 without converting, or I want to save space by downloading stream-quality music.

This is basically forcing the `else` part of [this section of code](https://github.com/flyingrub/scdl/blob/master/scdl/scdl.py#L352).

Does this feature sound reasonable, or is it useless?

**Comment by dpallone** [comment]
Would this be a command line argument?

**Comment by travs** [comment]
Yeah!

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/7cb0f8923265f275e8a953586229dded8f42db88
will be added soon to pypi
