### ISSUE TITLE
Downloading Personal Likes , 401 client error?

### ISSUE THREAD

**Issue by RoryOBigChief** [flyingrub/scdl#380]
Hi Guys, im not as super technical as most, but running the "scdl me -f" it is coming back with a 401 client error. 

Do i need to add in an AUTH token? or is the script literally just "scdl me -f"

Thank you

**Comment by ProdByJuliot** [comment]
As far as I know the tokens don't work at all with scdl because they basically banned that method specifically for scdl. You can specify a link for a user though with -l [yourprofile-url-here]

**Comment by ProdByJuliot** [comment]
Actually yeah I'm having issues too. [Here's what I get](https://github.com/flyingrub/scdl/issues/346#issuecomment-958144442)

**Comment by Dollabilliam** [comment]
I've also been facing a wide range of issues. I've uninstalled the application and reinstalled it with the suggested way of doing it ```pip3 install git+https://github.com/flyingrub/scdl```

Perhaps the return JSON has changed?

Here are some of the errors I've faced:

```
scdl -l https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500 -c --debug
. {return JSON containing track data}
.
.
Track n°1
Downloading Chris Lee (Li Yuchun 李宇春) - Only You (Clark Remix)
Downloading the original file.
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 280, in parse_url
    download_playlist(item)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 413, in download_playlist
    download_track(track_raw, playlist_info)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 576, in download_track
    filename, is_already_downloaded = download_original_file(track, title)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 470, in download_original_file
    r = requests.get(r.json()['redirectUri'], stream=True)
KeyError: 'redirectUri'
```

here's the same command from this morning:

```
scdl -l https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500 -c --debug
Soundcloud Downloader
{'--addtimestamp': False,
 '--addtofile': False,
 '--debug': True,
 '--download-archive': None,
 '--error': False,
 '--extract-artist': False,
 '--flac': False,
 '--force-metadata': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--max-size': None,
 '--min-size': None,
 '--no-album-tag': False,
 '--no-playlist-folder': False,
 '--onlymp3': False,
 '--path': None,
 '--remove': False,
 '--version': False,
 '-C': False,
 '-a': False,
 '-c': True,
 '-f': False,
 '-l': 'https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500',
 '-m': False,
 '-n': None,
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
Downloading to /Users/billy/Soundcloud...
https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500&client_id=a3e059563d7fd3372b49b37f00a00bcf
https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/dolla_billy/sets/mix-pt-2-soundcloud-has-a-500&client_id=2t9loNQH90kzJcsFCODdigxfp325aq4z
Failed to get item...
None
```

also from this morning but just for one track

```
scdl -l https://soundcloud.com/lockedclub/locked-club-tanzevat-edit
Soundcloud Downloader
Found a track
Downloading Locked Club - Tanzevat Edit
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 277, in parse_url
    download_track(item)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 579, in download_track
    filename, is_already_downloaded = download_hls_mp3(track, title)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 545, in download_hls_mp3
    url = get_track_m3u8(track)
  File "/usr/local/lib/python3.9/site-packages/scdl/scdl.py", line 534, in get_track_m3u8
    return r.json()['url']
KeyError: 'url'
```

Anyways, I'll try taking a deeper look into this this weekend

**Comment by 7x11x13** [comment]
You do need to specify your auth_token in the config file in order to use `scdl me`. The config file can be found at `C:/Users/user/.config/scdl/scdl.cfg` on Windows or `~/.config/scdl/scdl.cfg` on Linux.

**Comment by ProdByJuliot** [comment]
So then, in theory using `scdl me` is impossible because the client_id is banned? I tried running `scdl -l https://soundcloud.com/XXX` and it just returns `Invalid auth_token in C:\Users\XXX\.config\scdl\scdl.cfg` - which I just put in my profile URL for

**Comment by 7x11x13** [comment]
The client_id is not banned. auth_token is not the URL of your profile, it is the value of the "Authorization" header when you make a request to the SoundCloud v2 API. You can find it by visiting a page on SoundCloud after pressing F12 and going to the Network tab, then you can find one of the requests to the SoundCloud API and copy the Authorization header's value. This is only useful is you have a GO+ subscription because then you can download songs in higher quality (256 kbps AAC instead of 128 kbps MP3).
