### ISSUE TITLE
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by 7k50** [flyingrub/scdl#382]
Getting this error with `scdl==1.6.12`, using `Python 3.9.7`.

When running:

`scdl -l https://soundcloud.com/my_username -f -c --addtofile --path /my/path`

I get:

```
Traceback (most recent call last):
  File "/Users/username/Python/Virtual/py390/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/Users/username/Python/Virtual/py390/lib/python3.9/site-packages/scdl/scdl.py", line 185, in main
    parse_url(arguments['-l'])
  File "/Users/username/Python/Virtual/py390/lib/python3.9/site-packages/scdl/scdl.py", line 284, in parse_url
    download(item, 'favorites', 'likes')
  File "/Users/username/Python/Virtual/py390/lib/python3.9/site-packages/scdl/scdl.py", line 356, in download
    resources = client.get_collection(dl_url, token)
  File "/Users/username/Python/Virtual/py390/lib/python3.9/site-packages/scdl/client.py", line 19, in get_collection
    response.raise_for_status()
  File "/Users/username/Python/Virtual/py390/lib/python3.9/site-packages/requests/models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://api-v2.soundcloud.com/users/XXXXXXXX/track_likes?limit=200&client_id=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX&linked_partitioning=1
```

I was using the latest version of scdl, and have uninstalled it and re-installed it twice:

```
pip3 uninstall scdl
pip3 install git+https://github.com/flyingrub/scdl --upgrade
```

**Comment by Unreal-Dan** [comment]
I think everybody is getting this now, mine broke too

**Comment by myanmccann** [comment]
Same for me, 403 forbidden. I think it might have something do with the client ids for scdl being banned. I'm gonna take a closer look though.

**Comment by myanmccann** [comment]
I added a try except to catch when the download fails and a continue to retry. It was able to complete a playlist with 40 tracks and it took maybe 30 seconds longer. I'm not sure why sometimes the response is 403 but I don't think it's the client_id or rate limiting, since trying again helped.

**Comment by guthibs** [comment]
I get an 401 Client Error. Seems that the Client ID token is no longer allowed.

`requests.exceptions.HTTPError: 401 Client Error: Unauthorized for url: https://api-v2.soundcloud.com/me?oauth_token=&client_id=a3e05..etc`

**Comment by gpchelkin** [comment]
> I added some error handling to catch the status code 403 during the request and retry. It was able to complete a playlist with 40 tracks and it took maybe 30 seconds longer. I'm not sure why the response has status code 403 sometimes, but I don't think it's the client_id. It could be rate limiting, but I'm not really sure.

@def-hash could you please share your code somehow?

**Comment by Unreal-Dan** [comment]
Are we sure the solution is just retrying? 

Sounds like a good way to get ratelimited or hardblocked/banned.

Perhaps we need to generate our own client id tokens or something..?

**Comment by 7x11x13** [comment]
The problem is the user agent. SoundCloud now seems to block the default Python user agent, if you change the user agent header to e.g. firefox everything works fine.

**Comment by 7k50** [comment]
> The problem is the user agent. SoundCloud now seems to block the default Python user agent, if you change the user agent header to e.g. firefox everything works fine.

The user agent has to be changed within the `scdl` source code itself, right? If so, how can we do that? Unless there is some way extraneously create a fake user agent (wrapping `scdl` inside of something else?).

I use a command like this in the Terminal, as I guess most of us do:
`scdl -l https://soundcloud.com/USER -f -c --addtofile --path MYPATH`

**Comment by jz1** [comment]
> The problem is the user agent. SoundCloud now seems to block the default Python user agent, if you change the user agent header to e.g. firefox everything works fine.

Seems to work / fix for me, Thank you so much!

**Comment by 7x11x13** [comment]
> 
> 
> > The problem is the user agent. SoundCloud now seems to block the default Python user agent, if you change the user agent header to e.g. firefox everything works fine.
> 
> The user agent has to be changed within the `scdl` source code itself, right? If so, how can we do that? Unless there is some way extraneously create a fake user agent (wrapping `scdl` inside of something else?).
> 
> I use a command like this in Terminal, as I guess most of us do: `scdl -l https://soundcloud.com/USER -f -c --addtofile --path MYPATH`

If you're looking for an actively maintained fork, you can use mine at https://github.com/7x11x13/scdl

**Comment by guthibs** [comment]
> 
> If you're looking for an actively maintained fork, you can use mine at https://github.com/7x11x13/scdl

is working, thnx!

**Comment by Unreal-Dan** [comment]
> The problem is the user agent. SoundCloud now seems to block the default Python user agent, if you change the user agent header to e.g. firefox everything works fine.

that's what I figured, could we perhaps get a command line option to scdl to set the user agent?

**Comment by Ideekay** [comment]
> If you're looking for an actively maintained fork, you can use mine at https://github.com/7x11x13/scdl

Got this to _finally_ work, thanks @7x11x13!

If anyone else is a **_complete_** Python noob like me and is confused, here's what I did.

1. Replace existing `__init__.py` and `scdl.py` files with the updated ones from https://github.com/7x11x13/scdl/tree/master/scdl
2. Via command prompt, run the following commands to install the necessary files
     - `pip3 install pathvalidate`
     - `pip3 install soundcloud-v2>=1.1.1`

My .bat file works now, although it is re-downloading every song, rather than just the new ones. Is this normal?

**Comment by flyingrub** [comment]
I didnt got an email notification about this and as I am not going on github so often I did miss this issue. I will have a look at this asap, it was my plan to try to get a client ID automatically from the website so that this does not happen anymore.

**Comment by flyingrub** [comment]
@7x11x13 Would you be interested to become a maintainer of this repository, I do not have so much time to give to maintain this myself and it seems your fork is quite clean and has more features.

**Comment by 7x11x13** [comment]
Sure :)

**Comment by Unreal-Dan** [comment]
@7x11x13 is your newest version in pip? I tried updating via pip but still have the same issues.
