### ISSUE TITLE
FileNotFoundError: [WinError 2]

### ISSUE THREAD

**Issue by jketov** [flyingrub/scdl#389]
File "d:\__prog_python\python\lib\subprocess.py", line 1420, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]

**Comment by 7x11x13** [comment]
You need to have ffmpeg installed

**Comment by jketov** [comment]
It's working. I didn't check the availability of the library. Didn't think much about it, just put ffmpeg in the system32 folder. Thanks for the help.
