### ISSUE TITLE
me -f errors on certain playlists made before the Albums/EP SoundCloud update (I think)

### ISSUE THREAD

**Issue by ProdByJuliot** [flyingrub/scdl#392]
My guess is that playlists that were then converted into "albums or EPs" have issues with the date formatting that gives scdl issues. Here is an example. I have a lot more if they're needed. I was using `me` to download all of my liked tracks with `scdl me -f -c --addtimestamp --debug`. I got this error with and without soundcloud go+. --onlymp3 gives the same thing, however; just downloading the playlist with the link works. It's strange. There were "playlists" and "albums" (according to soundcloud) that caused this issue, but mostly the playlists.

  `File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\Scripts\scdl-script.py", line 33, in <module>
    sys.exit(load_entry_point('scdl==2.3.0', 'console_scripts', 'scdl')())
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\scdl.py", line 229, in main
    download_url(client, **python_args)
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\scdl\scdl.py", line 304, in download_url
    for i, like in enumerate(resources, 1):
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\soundcloud\soundcloud.py", line 438, in __call__
    yield self.convert_dict(resource)
  File "C:\Users\Carson Juliot\AppData\Local\Programs\Python\Python310\lib\site-packages\soundcloud\soundcloud.py", line 390, in convert_dict
    raise ValueError(f"Could not convert {d} to type {self.return_type}")`

`ValueError: Could not convert {'created_at': '2021-11-29T07:56:53Z', 'kind': 'like', 'playlist': {'artwork_url': None, 'created_at': '2015-02-27T01:37:21Z', 'duration': 2126796, 'id': 84662171, 'kind': 'playlist', 'last_modified': '2015-02-27T21:16:17Z', 'likes_count': 91197, 'managed_by_feeds': False, 'permalink': 'skrillex-diplo-present-jack-u', 'permalink_url': 'https://soundcloud.com/jacku/sets/skrillex-diplo-present-jack-u', 'public': True, 'reposts_count': 23957, 'secret_token': None, 'sharing': 'public', 'title': 'Skrillex & Diplo Present Jack Ü', 'track_count': 10, 'uri': 'https://api.soundcloud.com/playlists/84662171', 'user_id': 110803581, 'set_type': '', 'is_album': False, 'published_at': None, 'release_date': None, 'display_date': '2015-02-27T01:37:21Z', 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-000184531941-23l1ge-large.jpg', 'first_name': '', 'followers_count': 514580, 'full_name': '', 'id': 110803581, 'kind': 'user', 'last_modified': '2020-11-18T17:56:07Z', 'last_name': '', 'permalink': 'jacku', 'permalink_url': 'https://soundcloud.com/jacku', 'uri': 'https://api.soundcloud.com/users/110803581', 'urn': 'soundcloud:users:110803581', 'username': 'Jack Ü', 'verified': True, 'city': None, 'country_code': None, 'badges': {'pro': False, 'pro_unlimited': True, 'verified': True}, 'station_urn': 'soundcloud:system-playlists:artist-stations:110803581', 'station_permalink': 'artist-stations:110803581'}}} to type typing.Union[soundcloud.resource.like.TrackLike, soundcloud.resource.like.PlaylistLike]`

As a layman, it looks like  `'set_type': '', 'is_album': False, 'published_at': None, 'release_date': None, 'display_date': '2015-02-27T01:37:21Z'` could be causing the problems.

I apologize about the formatting. I'm new to programming and github. Let me know if I can do anything to help.
If anyone's still reading this: It's normal that it finishes below the total number of likes right?
Thanks for lookin at this.

**Comment by 7x11x13** [comment]
The problem was with 'published_at' being None; I updated the soundcloud.py library to make that field optional so it should work now
