### ISSUE TITLE
Im new to this so sorry if I'm dumb.

### ISSUE THREAD

**Issue by ReyZephlyn** [flyingrub/scdl#397]
I've installed Python, ffmpeg, and pip3 is installed. 

I'm not sure what I'm doing wrong as scdl seems to run fine but whenever I run a command through it it says "Failed to get item...".

I saw you reply to another issue post earlier and said that this should work ( scdl -l https://soundcloud.com/ranggaelectroscope2/karma-theme. ) So I tried it as an example but still got "Failed to get item.."

This is the first time I've ever done something like this so my apologies in advanced. Here is what I copied from Command

 --debug
Usage:
    scdl -l <track_url> [-a | -f | -C | -t | -p][-c][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--addtimestamp]
[--onlymp3][--hide-progress][--min-size <size>][--max-size <size>][--remove]
[--no-playlist-folder][--download-archive <file>][--extract-artist][--flac]
    scdl me (-s | -a | -f | -t | -p | -m)[-c][-o <offset>][--hidewarnings][--debug | --error][--path <path>][--addtofile][--addtimestamp]
[--onlymp3][--hide-progress][--min-size <size>][--max-size <size>][--remove]
[--no-playlist-folder][--download-archive <file>][--extract-artist][--flac]
    scdl -h | --help
    scdl --version

C:\Users\scrub>scdl -l https://soundcloud.com/ranggaelectroscope2/karma-theme
Soundcloud Downloader
Failed to get item...

**Comment by 7x11x13** [comment]
It looks like you are using an old version (check `scdl --version` is less than v2.3.5). Note that the scdl package on PyPI is outdated (something I hope on fixing some time soon). To install the latest version see https://github.com/flyingrub/scdl/wiki/Installation-Instruction

**Comment by ReyZephlyn** [comment]
Thanks a bunch! I updated my pip. I get this when I enter the update command "pip3 install git+https://github.com/flyingrub/scdl --upgrade"

C:\Users\scrub>pip3 install git+https://github.com/flyingrub/scdl --upgrade
Collecting git+https://github.com/flyingrub/scdl
  Cloning https://github.com/flyingrub/scdl to c:\users\scrub\appdata\local\temp\pip-req-build-kmjq_9k0
  ERROR: Error [WinError 2] The system cannot find the file specified while executing command git version
ERROR: Cannot find command 'git' - do you have 'git' installed and in your PATH?

C:\Users\scrub>

Am I doing something wrong or is the updated file just not available?

**Comment by 7x11x13** [comment]
You need to install git as well: https://git-scm.com/

**Comment by ReyZephlyn** [comment]
Holy tart it works now! Tysm for helping dude.
