### ISSUE TITLE
Download 256kbps audio with Go+ account?

### ISSUE THREAD

**Issue by whatsupimr** [flyingrub/scdl#401]
Hello, not really an issue, just a question. I have a Soundcloud Go+ account (and my personal oauth token), and I've input my oauth token into the config file. However, when I go to download any track, it always ends up as an MP3. Is there any way to download the M4A files, since I have a Go+ account? Thanks.

**Comment by 7x11x13** [comment]
Some tracks are only available in mp3, can you provide some links so I can check if they're available in higher quality? It should download in the highest quality available.

**Comment by whatsupimr** [comment]
> Some tracks are only available in mp3, can you provide some links so I can check if they're available in higher quality? It should download in the highest quality available.

I have used a different version of SCDL in the past through a Discord bot that has downloaded these in m4a before. But here's a couple examples.

https://soundcloud.com/channeldigital/keep-me-in-ur-pocket
https://soundcloud.com/dovescry/beloved-ft-wicca-phase-springs?in=dovescry/sets/looks-bw-beloved

**Comment by 7x11x13** [comment]
Yes, I'm able to download those as 256 kbps AAC. Since you have GO+ and your auth token in the config, I'm not sure what the issue could be. Maybe you have "high quality audio" turned off in SoundCloud's streaming settings?

**Comment by whatsupimr** [comment]
I will check that and get back to you. Thank you.

**Comment by whatsupimr** [comment]
> Yes, I'm able to download those as 256 kbps AAC. Since you have GO+ and your auth token in the config, I'm not sure what the issue could be. Maybe you have "high quality audio" turned off in SoundCloud's streaming settings?

So I went into my Soundcloud settings and enabled High-Quality Audio playback. I retrieved my access token through my cookies (just to be sure it hadn't expired), and tried to download the first track I sent you yesterday. Surprisingly, it is still saving as an MP3 file. I have attached my .cfg file as well as the command I am using to run SCDL, as it does not work for me with the regular command. Thank you for all the help!

https://imgur.com/a/hpvSIYy

**Comment by 7x11x13** [comment]
The `scdl.cfg` there is actually the default config, the one you should edit would be at `C:\Users\Jonathan\.config\scdl\scdl.cfg`. Also you shouldn't post your auth token publicly, log out & log back in to soundcloud to get a new auth token so no one messes with your account!

**Comment by whatsupimr** [comment]
> The `scdl.cfg` there is actually the default config, the one you should edit would be at `C:\Users\Jonathan\.config\scdl\scdl.cfg`. Also you shouldn't post your auth token publicly, log out & log back in to soundcloud to get a new auth token so no one messes with your account!

Changed it in the .cfg file you pointed to, and it works! Thank you so much man, you're a legend <3

**Comment by bakeiro** [comment]
Hi!

I'm using Linux, my `scdl.cfg` config file is empty, I pasted my Oauth token there but makes the program fail... should the `scdl.cfg`  not being empty? (I had to create it)
