### ISSUE TITLE
--min-size not working?

### ISSUE THREAD

**Issue by altmank** [flyingrub/scdl#409]
Running the script with  --min-size 2m, but am getting files downloaded that are 500ish KB (they are SoundCloud GO files usually). Does this feature not work or am I using it wrong?

**Comment by 7x11x13** [comment]
Could you provide example input? Also, make sure you're on the latest version (v2.6.2)

**Comment by altmank** [comment]
scdl -l https://soundcloud.com/<mySCUser> -f -c --download-archive archive.txt --path "G:\Music\Soundcloud" --min-size 2m

**Comment by altmank** [comment]
I'm on 2.4.0, so will need to upgrade and see if that makes a difference. It has been an issue for awhile for me though, at least a few versions.

**Comment by altmank** [comment]
Upgraded to 2.6.2 and it looks like it may be working now.

I tested a Go file and got "File not within --min-size and --max-size bounds"

Maybe it was fixed between 2.4 and 2.6.2. Thanks for the quick comments.
