### ISSUE TITLE
Run as deamon?

### ISSUE THREAD

**Issue by surfacescan** [flyingrub/scdl#42]
Hey there - I want to combine your amazing application with piMusicBox.

Ultimately I would like to run scdl as a daemon which is always checking to see if a user (me) has any new "liked" tracks on my soundcloud and then it grabs them and puts it into a folder which PiMusicBox will grab and add to a playlist.

What would I need to do to run your app as a daemon?

would it be possible to run multiple instances if I wanted it to monitor several soundcloud users/tokens at the same time?

**Comment by flyingrub** [comment]
i like the idea, i never though about it before, i will see what i can do.

**Comment by surfacescan** [comment]
Cool!  Let me know if you make any progress!  Otherwise, so far it is amazing as is.  nice work!

I guess a cron job might be helpful

**Comment by flyingrub** [comment]
yep, it has at first be designed to be run with a cron job :)
