### ISSUE TITLE
Attach artist informormation to wav files.

### ISSUE THREAD

**Issue by StevenDoesStuffs** [flyingrub/scdl#426]
Currently for all wav files (which I'm guessing are original files) there is no listed artist in the metadata like their is for other soundcloud downloads. I'd be willing to PR this if y'all would like this change to be implemented. I think it'd be pretty consistent with the way this program handles original files currently since it's already editing titles for original files (see #244).

**Comment by littletsu** [comment]
Wav tagging support was already added in #417, but the tags are only supported in some players. Try downloading a wav file with the --force-metadata argument and opening it in foobar2000 or MusicBee, the tags should be displayed properly in these players
