### ISSUE TITLE
Attempts at downloading gives the same output as --help

### ISSUE THREAD

**Issue by WindowsRefundDay** [flyingrub/scdl#427]
I'm not a coder but I'll try providing the info I can.

OS: Windows 11 Home
Using CMD in Terminal

Input:
`C:\Users\joelj>scdl -I https://soundcloud.com/sadboyprolific/whats-going-on-w-powfu-rxseboy-prodoceanbeats`
`Usage:
    scdl (-l <track_url> | me) [-a | -f | -C | -t | -p | -r][-c | --force-metadata]
    [-n <maxtracks>][-o <offset>][--hidewarnings][--debug | --error][--path <path>]
    [--addtofile][--addtimestamp][--onlymp3][--hide-progress][--min-size <size>]
    [--max-size <size>][--remove][--no-album-tag][--no-playlist-folder]
    [--download-archive <file>][--sync <file>][--extract-artist][--flac][--original-art]
    [--original-name][--no-original][--only-original][--name-format <format>]
    [--strict-playlist][--playlist-name-format <format>][--client-id <id>]
    [--auth-token <token>][--overwrite][--no-playlist]`

`C:\Users\joelj>`

Also screenshot:
![image](https://user-images.githubusercontent.com/88746308/178345551-62128838-b045-4bb7-9a84-d70592a82b53.png)
Installed using pip

**Comment by 7x11x13** [comment]
`-I` (uppercase i) should be `-l` (lowercase L) in your command
