### ISSUE TITLE
HTTPError: 403 Client Error: Forbidden for url after adding auth token to config

### ISSUE THREAD

**Issue by aserbremen** [flyingrub/scdl#429]
I can use scdl without setting `auth_token` in `~./config/scdl/scdl.cfg` (only downloading low quality). I want to download the high quality, so I set the settings for high quality audio in my soundcloud account Go+ and try to use my auth token. But when I get my auth token using [mopidy](https://mopidy.com/ext/soundcloud/#authentication) and put it into the config I get the following error: 

```
(scdl) andi@pc:~/Music/soundcloud$ scdl -l https://soundcloud.com/marlonhoffstadt/dj-daddy-trance-day-n-night 
Soundcloud Downloader
Traceback (most recent call last):
  File "/home/andi/miniconda3/envs/scdl/bin/scdl", line 8, in <module>
    sys.exit(main())
  File "/home/andi/miniconda3/envs/scdl/lib/python3.7/site-packages/scdl/scdl.py", line 168, in main
    if (token or arguments["me"]) and not client.is_auth_token_valid():
  File "/home/andi/miniconda3/envs/scdl/lib/python3.7/site-packages/soundcloud/soundcloud.py", line 140, in is_auth_token_valid
    self.requests["me"](auth_token=self.auth_token)
  File "/home/andi/miniconda3/envs/scdl/lib/python3.7/site-packages/soundcloud/soundcloud.py", line 450, in __call__
    r.raise_for_status()
  File "/home/andi/miniconda3/envs/scdl/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url:
```

I believe the forbidden url contains the token, so I didn't paste it here. 

Also the conda environment, creates two more `scdl.cfg` files. I tried setting the auth token there, but it didn't help either.

**Comment by littletsu** [comment]
scdl uses soundcloud API V2 while Mopidy gives you an auth token for soundcloud API V1. To get an auth token and client id for the soundcloud API V2 you will have to get it using your browser's developer tools and analizing the network requests. I'll describe how to do this process in Firefox, although it should be pretty similar in other browsers:

1. Open soundcloud while logged in, right click and click on Inspect Element to open the developer tools
![img](https://user-images.githubusercontent.com/38116582/180386127-b89a29bb-5c62-47d4-a6b3-145dfe89ea7c.png)
2. Go to the Network tab
![img2](https://user-images.githubusercontent.com/38116582/180386431-24c08057-128b-47e9-b77f-7d28e57e75fe.png)
3. Refresh the page (don't close the developer tools yet)
4. Once the page reloads, you'll see lots of requests in the network tab, click on any request which url is `api-v2.soundcloud.com`. 
![img3](https://user-images.githubusercontent.com/38116582/180387858-7312e22b-eb89-4fd8-a9b0-00c67a7f4eab.png)
5. Something like this will come up when you click a request. You can now get the `client_id` by copying it from the highlighted part on the url
![image](https://user-images.githubusercontent.com/38116582/180388234-75edcfea-70ca-4772-9143-21e26b520e81.png)
6. Now scroll down until you get to Request Headers and find the **Authorization** header. The value after the : is the `auth_token`
![img4](https://user-images.githubusercontent.com/38116582/180389049-c0039ba3-251a-4daa-8d27-d752caf52350.png)
7. Now you can put them in your scdl.cfg file like so:
![image](https://user-images.githubusercontent.com/38116582/180389495-d32fe324-5eae-4814-8381-2c2b17a859d5.png)



I'm not sure if there is an easier way to do this, but I tried it and it works with scdl.

**Comment by littletsu** [comment]
Also note that the `client_id`'s and `auth_token`'s from this method expire after some weeks/months, so you'll have to repeat this process once they expire

**Comment by aserbremen** [comment]
Thanks, works like a charm!

**Comment by 7x11x13** [comment]
> I'm not sure if there is an easier way to do this, but I tried it and it works with scdl.

An easier way would be to look at the Storage tab and find the oauth_token cookie
