### ISSUE TITLE
Am I missing something completely? (I'm without a doubt a coding noob)

### ISSUE THREAD

**Issue by ligunn** [flyingrub/scdl#430]
This is my code inputted into cmd (with admin access):

C:\WINDOWS\system32>scdl -1 https://soundcloud.com/liamgunning3/sets/whilst-3

This is the immediate response from scdl script:

C:\WINDOWS\system32>scdl -1 https://soundcloud.com/liamgunning3/sets/whilst-3 me
Usage:
    scdl (-l <track_url> | me) [-a | -f | -C | -t | -p | -r][-c | --force-metadata]
    [-n <maxtracks>][-o <offset>][--hidewarnings][--debug | --error][--path <path>]
    [--addtofile][--addtimestamp][--onlymp3][--hide-progress][--min-size <size>]
    [--max-size <size>][--remove][--no-album-tag][--no-playlist-folder]
    [--download-archive <file>][--sync <file>][--extract-artist][--flac][--original-art]
    [--original-name][--no-original][--only-original][--name-format <format>]
    [--strict-playlist][--playlist-name-format <format>][--client-id <id>]
    [--auth-token <token>][--overwrite][--no-playlist]

Do I need to essentially copy, edit, and paste that entire script^? I just checked and have mutagen, etc. up to date

[edit: I have a soundcloud go+ account, and put my client_id and OAuth 2 token into the .cfg file.]

**Comment by littletsu** [comment]
Use `scdl -l https://soundcloud.com/liamgunning3/sets/whilst-3` (Note the
lowercase L letter, instead of a 1)
