### ISSUE TITLE
Download all favorites caps at around ~100 downloads.

### ISSUE THREAD

**Issue by zunayed** [flyingrub/scdl#45]
For some reason running `scdl -f- c` will only download about 100 tracks from my favorites list.

running
```py
favorites = client.get('/users/' + str(user.id) + '/favorites', limit=500)
```
yields me back about 190+ results though

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/blob/master/scdl/scdl.py#L284
we download the user favorites 10 by 10 in order to optimise the download speed.
I need a log or something to tell you what occured

**Comment by flyingrub** [comment]
i close, if you have any update keep us up to date :)

**Comment by cschmittiey** [comment]
using ```scdl me -c -f --onlymp3 --debug``` 
I get the same issue, log here: https://paste.fedoraproject.org/301908/3026731/
