### ISSUE TITLE
Keep track of how many already downloaded?

### ISSUE THREAD

**Issue by surfacescan** [flyingrub/scdl#46]
Hey there - loving your app. Amazing.

It would be excellent if on the local side, there was a json file or something that knew what had been already downloaded so that when I tru something like scdl -l www.soudncloud.com/userx -a it will know if anything new has been added since last time without needing to go through the whole list.

I hope that makes sense?

**Comment by surfacescan** [comment]
To elaborate - here it looks like soundcloud API provides a way to get a list of a users activities: http://stackoverflow.com/questions/14102567/how-to-access-a-users-stream and it seems that if we also kept a local file to compare against, it could be quite quick to know what new files need to be downloaded to sync all of a users likes or reposts or playlists etc...

What do you think?

**Comment by flyingrub** [comment]
but the script already know to stop if it encounter a track that already exist, i don't understand why we need something like in your idea ?

**Comment by flyingrub** [comment]
i think that we can close this issue :), keep me updated if you see any inconvenient
