### ISSUE TITLE
--flac not working and mp3s only download up to 128kpbs

### ISSUE THREAD

**Issue by atryxun** [flyingrub/scdl#461]
I add the --flac section to my prompt but it bypasses it entirely and downloads the m4a. Also, the mp3s don't go up to 250k. Are there any fixes?

**Comment by gabltz** [comment]
actually the same issue, using widnows and ffmpeg is correctly installed and in the path of windows
![image](https://github.com/flyingrub/scdl/assets/47774056/2f0c5763-bc86-454f-b68d-138775a6faa1)

**Comment by 7x11x13** [comment]
--flac only converts to flac when the original file download is available in lossless quality (wav/aiff), which requires the artist to enable downloads for the track. The highest quality audio available from SoundCloud if the original download is not available is 256 kbps AAC (only if you have GO+, and the song was uploaded in high enough quality). If you do not have GO+ or the song was uploaded in not lossless quality, the only transcodings provided by SoundCloud are 128 kbps MP3 or 128 kbps Opus (which you can choose over mp3 with the --opus flag).
