### ISSUE TITLE
How to get the auth token?

### ISSUE THREAD

**Issue by tomo0300** [flyingrub/scdl#474]
Heyy,
I have SC Go+ and would like to download all the songs - including those contained in Go+ - in full length. So far they are all only 30 seconds long. 
I think I need to set my auth token for this, but I'm not sure if that's right and if so, where I get it from or how I generate it.
Or is there no way to download all the songs with your tool? (That would also be fine and should not sound mean :) )

**Comment by 7x11x13** [comment]
https://github.com/flyingrub/scdl/wiki/Installation-Instruction#authentication
