### ISSUE TITLE
[FEATURE REQ] prefer opus over mp3

### ISSUE THREAD

**Issue by HeartbeatingForCenturies** [flyingrub/scdl#475]
most new songs i've seen so far now provide an opus stream which has a higher bitrate than the traditional MP3-128 stream and lower filesize, it is also a free feature not requiring an auth token.

**Comment by 7x11x13** [comment]
Can you give an example?

**Comment by HeartbeatingForCenturies** [comment]
![spek_Bf8RkN3Vxa](https://github.com/flyingrub/scdl/assets/45168911/2f41c207-b7e4-4b27-b917-96231fb4b6d0)
song - https://soundcloud.com/jawnino/westfield

**Comment by 7x11x13** [comment]
Added in the latest version with the `--opus` flag
