### ISSUE TITLE
Having trouble with title tags on playlist download

### ISSUE THREAD

**Issue by samuel-clement** [flyingrub/scdl#486]
I am unable to make tracks in a playlist download without just the track title as filename. I can only get them to download as  playlistname_artist_trackname. Not sure if this is possible to change. Any help is much appreciated!

**Comment by samuel-clement** [comment]
I was able to achieve what I was looking for with the following command: 
scdl --playlist-name-format "{title}" -l URL

**Comment by jamesryan-dev** [comment]
is there a way to edit this in a config file or sometihng?
