### ISSUE TITLE
Delete *.scdl.lock after all processes are complete

### ISSUE THREAD

**Issue by adithayyil** [flyingrub/scdl#490]
I am not sure how the behaviour is in Windows. But in UNIX, the lock files are not deleted when released because of race conditions. See [here](https://stackoverflow.com/questions/58098634/why-does-the-python-filelock-library-delete-lockfiles-on-windows-but-not-unix). For scdl specifically, I would assume that the lock files are not needed when there are no scdl processes running anymore? If so, we need to have some sort of deleting mechanism because directories would get messy after some point.

**Comment by 7x11x13** [comment]
Oh that's annoying... I guess we should keep the lockfiles in a tempdir as suggested here (if we are not on Windows): https://github.com/tox-dev/filelock/issues/76#issuecomment-696409014

**Comment by adithayyil** [comment]
yup that would work I think. we can also keep it hidden like `./.scdl.locks/`, and when the process exits or finishes we can simply remove the dir.

**Comment by 7x11x13** [comment]
Should be fixed now
