### ISSUE TITLE
401 Client Error

### ISSUE THREAD

**Issue by BassemGhoniem** [flyingrub/scdl#53]
More than one url show this message to me
it's new issue :(

Error resolving url, retrying...
Could not resolve url 
401 Client Error: Unauthorized

**Comment by Spotlight0xff** [comment]
Can you give us please one or more examples?

**Comment by flyingrub** [comment]
Test the new version on pypi uninstall and reinstall

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/issues/54#issuecomment-95956541

**Comment by djclarkson** [comment]
Same error with latest release.

**Comment by uahim** [comment]
same here

**Comment by flyingrub** [comment]
for now you will have to install it from the github source...
i changed the client_id there.

**Comment by flyingrub** [comment]
fixed and uploaded a new version on pypi
