### ISSUE TITLE
Could not find a version that satisfies the requirement scdl

### ISSUE THREAD

**Issue by salahmo7sen** [flyingrub/scdl#54]
sudo -H pip3 install scdl
Collecting scdl
  Could not find a version that satisfies the requirement scdl (from versions: )
  No matching distribution found for scdl

**Comment by ayush--s** [comment]
getting a similar error on my windows: 
    C:\Users\user {git}
    pip install scdl
    Collecting scdl
      Could not find a version that satisfies the requirement scdl (from versions: )
      No matching distribution found for scdl

**Comment by flyingrub** [comment]
did you have a previous installation of scdl ?

**Comment by salahmo7sen** [comment]
no i don't !

**Comment by flyingrub** [comment]
i had few problem with soundcloud the last few days (they deleted my account), that's why i removed scdl from pypi, but now it should be back... ?
I will look into it when i will get my laptop back.

**Comment by salahmo7sen** [comment]
ok. thank you :))

**Comment by flyingrub** [comment]
i uploaded a new version on pypi let me now if it works now ;)
