### ISSUE TITLE
Error resolving url, retrying....

### ISSUE THREAD

**Issue by djclarkson** [flyingrub/scdl#55]
Pretty much same issue as before. 

Ran the updater yesterday. 

$scdl --version
v1.2
$scdl -l https://soundcloud.com/nicolemoudaber/in-the-mood-episode-52
Error resolving url, retrying...
Could not resolve url https://soundcloud.com/nicolemoudaber/in-the-mood-episode-52
401 Client Error: Unauthorized

**Comment by flyingrub** [comment]
uninstall scdl then reinstall, the latest update is 1.3.2

**Comment by djclarkson** [comment]
Success thanks.
