### ISSUE TITLE
Bug: Download stops after 100 tracks

### ISSUE THREAD

**Issue by davidfischer-ch** [flyingrub/scdl#60]
It's because of this strange code:

    tracks = client.get('/users/' + str(user.id) + '/tracks', limit=10, offset=offset)
    for track in tracks:
        for track in tracks:
            ....

limit = 10, so 10 x 10 = 100, is that a conspiracy?

I already have a working solution, but I wanna warn you first.

**Comment by flyingrub** [comment]
https://developers.soundcloud.com/blog/offset-pagination-deprecated

**Comment by davidfischer-ch** [comment]
Does the links means please implement new pagination scheme into `get_all`?

**Comment by flyingrub** [comment]
It means that we should use the soundcloud's recommended way ;)
