### ISSUE TITLE
Make code DRY

### ISSUE THREAD

**Issue by davidfischer-ch** [flyingrub/scdl#61]
Don't use many time same code but make an utility function.
For example, client.get is called many times with same pattern.

**Comment by flyingrub** [comment]
waiting for your pull request ;)

**Comment by flyingrub** [comment]
the fact that you use set isn't great because we lose the order of the element.
If i just want to sync with the old one i downloaded i can't now.

I think we should write our own soundcloud wrapper in python because the official one is not up to date...
It doesn't support the new linked pagination option.

**Comment by Spotlight0xff** [comment]
It's opensource? Why not just collaborate with them? Would be a pretty big project...

**Comment by flyingrub** [comment]
https://github.com/soundcloud/soundcloud-python

**Comment by Spotlight0xff** [comment]
I see. Better fork it? Or do you want to make it all from scratch?

**Comment by davidfischer-ch** [comment]
@flyingrub : I am not sure to understand. Why do you think the order of the tracks impact the code downloading them? I used my fork many times for updating my collection and it works properly.

In addition, f you want to set the order of the elements while iterating, you only have to use sorted(the_evil_set) and use the key key argument if necessary.

For the issue with the SoundCloud wrapper, if the issue is only related to the newest linked pagination, then its not worthy to make a new project from scratch. In contrary, if you feel like you have a better overall design, then it can be an idea to develop a new wrapper.

**Comment by flyingrub** [comment]
>> Why do you think the order of the tracks impact the code downloading them?
Because if i some track are new : 
1) if the option -c is not used it will stop at first track.
2) it will test every track for nothing.

**Comment by davidfischer-ch** [comment]
Hello,

Did you have a unit-test for testing this feature?

I did not found the reference to the fact the API will return sorted elements.
Its probably better to sort tracks using python sorted() based on the right element attribute.

**Comment by flyingrub** [comment]
i use this api since 2 year and it's always sorted by the latest one liked / upload /ect.
Wouldn't it be easier, to use List or something that is ordered ?

**Comment by davidfischer-ch** [comment]
Please update the code as you'd like to implement it.
Maybe someone else has another idea?

I used a set to ensure every element appear once.

**Comment by flyingrub** [comment]
the script already handle double song :)
it skip them.

**Comment by davidfischer-ch** [comment]
Nice!

But its better to ensure there are no duplicate elements at the lowest level possible, the "library" :-)
That way we have a consistent progress report (total = len(...)). Etc.

**Comment by flyingrub** [comment]
Yep, it's good to have a progress. ;)
I will try to use something ordered if i find some time (not for now).

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/89840bfa5bdfa9aae64fc4168531e32c56553101
