### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 15: ordinal not in range(128)

### ISSUE THREAD

**Issue by gruzilla** [flyingrub/scdl#62]
i am using docker ( https://github.com/dghubble-docker/python3.git ) to run scdl.
i added the following to the Dockerfile:

```
RUN pip3 install scdl
ADD config/scdl.cfg /root/.config/scdl/scdl.cfg
```

to run the container and inside it scdl i start the container the following way:

`docker run -t -i dghubble/python3`

now `scdl -l [someurl]` works perfectly. really awesome, loving it!!!
but

`scdl me -f`

printed an error because my name contains a "ö".
after changing my name this error was gone.

however it seems as if there is a problem with one of the songs in my favorites.
i still get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 120, in main
    download_user_favorites(who_am_i())
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 291, in download_user_favorites
    log('Favorite n\xb0%d' % (count), strverbosity=1)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 67, in log
    print(colored(str, 'white'))
UnicodeEncodeError: 'ascii' codec can't encode character '\xb0' in position 15: ordinal not in range(128)
```

is that because of my docker environment? it shouldn't be, should it? because its based on ubuntu and my host system is arch.

using `--error` fixes the problem, but some files seem to be missing (its a looong playlist, hard to compare).

i really appreciate the effort put into this script! nice work!

**Comment by gruzilla** [comment]
Not sure if this is linked to #37

**Comment by flyingrub** [comment]
it seems it's related to your docker, cause the error you link only appear on windows.

**Comment by gruzilla** [comment]
Unfortunately i got another error of the same kind, but on a different line of code:

```
Traceback (most recent call last):
  File "/usr/local/bin/scdl", line 9, in <module>
    load_entry_point('scdl==1.3.2', 'console_scripts', 'scdl')()
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 120, in main
    download_user_favorites(who_am_i())
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 292, in download_user_favorites
    download_track(track)
  File "/usr/local/lib/python3.4/dist-packages/scdl/scdl.py", line 378, in download_track
    title = title.encode('utf-8', 'ignore').decode(sys.stdout.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1: ordinal not in range(128)
```

**Comment by gruzilla** [comment]
Ok. Solved it:

After some reading, i found  that docker initializes its shell with the wrong default encoding.
Starting the container the following way fixes all unicode-problems.

Sorry to bother.

FIX:

`docker run -ti --rm -e LANG=C.UTF-8 dghubble/python3`

Maybe this also helps @dghubble ?

**Comment by dghubble** [comment]
@gruzilla thanks, I've added that
