### ISSUE TITLE
High CPU usage in tmux

### ISSUE THREAD

**Issue by Spaghetti-Cat** [flyingrub/scdl#65]
If I run `scdl` in `tmux` the `tmux` process takes up 15-20% CPU (on a 1.9GHz dual-core CPU). High CPU usage happens whether I run `tmux` from a tty or a terminal emulator (Konsole). High CPU usage doesn't happen if I run `scdl` outside of `tmux` in Konsole.

In my experience this is probably caused by the progress bar being redrawn waaay too often. If I run `scdl -l some_url &> /tmp/stdout.txt` (thus hiding the progress bar) the high CPU usage problem doesn't occur.

Would you consider reducing the progress bar's incredibly high refresh rate? The human eye can't even keep up when the numbers change so quickly.

PS: Many thanks for this very useful program :)

**Comment by flyingrub** [comment]
this bar is displayed by wget-python, i can't change it's refresh rate...

**Comment by Spotlight0xff** [comment]
Well, we could add an option to disable the progressbar.
Basically just changing https://github.com/flyingrub/scdl/blob/master/scdl/scdl.py#L398 to
`wget.download(url, filename)` to `wget.download(url, filename, bar=None)`
See https://bitbucket.org/techtonik/python-wget/src/8341a80f1c8f2a348fb69b01166040dc443ac21d/wget.py?at=default#cl-283
wget-python supports the bar-parameter (bar_thermometer, bar_adaptive or None).

**Comment by flyingrub** [comment]
yep, this could help

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/31562a3d7910b9c4a069000c517abaec1ab222f5

**Comment by Spaghetti-Cat** [comment]
Ahh, thank you for adding this option, I appreciate. But I think "--tmux" is a bad name because what the option does is hides the progress bar, so "--hide-progress" or "--no-progress" is a better name. Everyone else will be confused by "--tmux" in the help, when they see it.

**Comment by flyingrub** [comment]
exact :)
i will change this.

**Comment by flyingrub** [comment]
fixed.
