### ISSUE TITLE
Offset isn't added to current track number

### ISSUE THREAD

**Issue by Sinnlosvoll** [flyingrub/scdl#72]
If scdl is calle with an offset of e.g. 18, it will start with track 1 instead of 19/18 depending on how offsets are handled.

This would clear up the interface a bit.

**Comment by KostyaKow** [comment]
I get same thing

**Comment by flyingrub** [comment]
fixed in last commit https://github.com/flyingrub/scdl/commit/4f10341dc091cd91d38059caa044dfa03c8ddebd for all download type.
