### ISSUE TITLE
The -f option doesn't enable to download me liked tracks (only 86)

### ISSUE THREAD

**Issue by nico2610** [flyingrub/scdl#77]
Hello,

I tested to download all my liked tracks with the -f option but the process stop after 86 downloads.
The last output is : 

```
Favorite n°86
Downloading <track_name>

All users favorites downloaded!
```

The command that I have tested is : 

```
scdl me -f -c --debug
```

I tried direclty with the url (without token) too : 

```
scdl -l https://soundcloud.com/prismeprod/ -f -c
```
but same behaviour.
Is there a limit to download from soundcloud or something like that ?

**Comment by flyingrub** [comment]
which version ?
The version on github should fix that but i cannot push it to pypi for now.

**Comment by nico2610** [comment]
I got the lastest I think (git clone) : 

```
scdl --version
v1.3.2
```
Is that the good one ?
I found a workaround with adding the offset option 

````
scdl me -f -c -o 30
````

Whit that, the most of tracks are already downloaded but the process is downloading tracks a bit more.
The annoying is that I don't know exactly how much favorites I have (but it's certainly more than 86 ;-) )

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/blob/master/scdl/__init__.py#L5

**Comment by flyingrub** [comment]
any update ?

**Comment by flyingrub** [comment]
latest version pushed to pypi. feel free to reopen this issue if there is still one.

**Comment by nico2610** [comment]
Sorry for the last update, I don't have been time to test yesterday. It works fine, thank you.
