### ISSUE TITLE
ubuntu 14.04 Invalid token...

### ISSUE THREAD

**Issue by zaibfridi** [flyingrub/scdl#78]
i install the all packages

also generate the token from soundcloud and place it in /scdl/config/scdl.cfg

but when i am trying to do 

scdl me -a --debug

this give me this error 
Soundcloud Downloader
{'--addtofile': False,
 '--debug': True,
 '--error': False,
 '--help': False,
 '--hidewarnings': False,
 '--onlymp3': False,
 '--path': None,
 '--version': False,
 '-a': True,
 '-c': False,
 '-f': False,
 '-l': None,
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': True}
Downloading to /home/user/Documents...

Invalid token...

**Comment by Spotlight0xff** [comment]
what's your scdl.cfg?

**Comment by zaibfridi** [comment]
[scdl]
auth_token = 1-126453-90543453-xxxxxxxx
path = /usr/local/bin/scdl

**Comment by Spotlight0xff** [comment]
the path should be a directory in which scdl downloads the music.

**Comment by flyingrub** [comment]
The path is where the music is downloaded. Not where the script is :)
I should add documentation about that

**Comment by zaibfridi** [comment]
okay now i put this 

[scdl]
auth_token = 1-126453-90543453-xxxxxxx
path = /home/user/Documents/

again facing the same issue

**Comment by zaibfridi** [comment]
i think i am mission some thing .....!!
this is the pip freeze ..... !! 

Babel==1.3
Cheetah==2.4.4
CherryPy==3.2.2
Jinja2==2.7.3
MarkupSafe==0.23
PAM==0.4.2
Pillow==2.3.0
Pygments==2.0.2
Pykka==1.2.0
Routes==2.0
Sphinx==1.3.1
Twisted-Core==13.2.0
Twisted-Web==13.2.0
WebOb==1.3.1
adium-theme-ubuntu==0.3.4
alabaster==0.7.6
apt-xapian-index==0.45
argparse==1.2.1
chardet==2.0.1
colorama==0.2.5
command-not-found==0.3
configparser==3.3.0r2
debtagshw==0.1
debtcollector==0.5.0
defer==1.0.6
dirspec==13.10
docopt==0.6.2
docutils==0.12
duplicity==0.6.23
ecdsa==0.13
extras==0.0.3
eyeD3==0.7.8
fixtures==1.3.1
flake8==2.4.1
fudge==1.0.3
git-review==1.25.0
gyp==0.1
html5lib==0.999
httplib2==0.8
iso8601==0.1.10
libvirt-python==1.2.2
linecache2==1.0.0
lockfile==0.8
lxml==3.3.3
mccabe==0.3.1
mock==1.0.1
msgpack-python==0.4.6
mutagen==1.30
netaddr==0.7.15
netifaces==0.10.4
nose==1.3.7
oauthlib==0.6.1
oneconf==0.3.7.14.04.1
oslo.config==1.13.0
oslo.context==0.4.0
oslo.i18n==2.0.0
oslo.log==1.6.0
oslo.serialization==1.6.0
oslo.utils==1.7.0
paramiko==1.15.2
pbr==1.2.0
pep8==1.5.7
pexpect==3.1
piston-mini-client==0.7.5
py==1.4.26
pyOpenSSL==0.13
pycrypto==2.6.1
pycups==1.9.66
pycurl==7.19.3
pyflakes==0.8.1
pygobject==3.12.0
pyserial==2.6
pysmbc==1.0.14.1
python-apt==0.9.3.5ubuntu1
python-debian==0.1.21-nmu2ubuntu2
python-mimeparse==0.1.4
python-subunit==1.1.0
pytz==2015.4
pyxdg==0.25
reportlab==3.0
repoze.lru==0.6
requests==2.7.0
scdl==v1.3.2
selenium==2.46.0
sessioninstaller==0.0.0
simplejson==3.8.0
six==1.9.0
snowballstemmer==1.2.0
software-center-aptd-plugins==0.0.0
soundcloud==0.4.1
sphinx-rtd-theme==0.1.8
ssh-import-id==3.21
stevedore==1.5.0
system-service==0.1.6
termcolor==1.1.0
testrepository==0.0.20
testtools==1.8.0
texttable==0.8.3
tox==1.6.1
traceback2==1.4.0
unittest2==1.1.0
unity-lens-photos==1.0
urlgrabber==3.9.1
urllib3==1.7.1
vboxapi==1.0
virtinst==0.600.4
virtualenv==12.0.7
virtualenv-clone==0.2.5
virtualenvwrapper==4.5.1
wget==2.2
wheel==0.24.0
wrapt==1.10.4
ws4py==0.3.2
wsgiref==0.1.2
wxPython==2.8.12.1
wxPython-common==2.8.12.1
xdiagnose==3.6.3build2
xvfbwrapper==0.2.4
zope.interface==4.0.5

**Comment by Spotlight0xff** [comment]
On which OS are you?

**Comment by flyingrub** [comment]
by the way your scdl is not up to date : `scdl==v1.3.2`. the latest version is v1.4.0b1

**Comment by zaibfridi** [comment]
ubuntu 14.04 LTS is my OS
and i am trying to to update the scdl
i run this command
i tried both pip and pip3 in this command

sudo pip3 install -Iv scdl==1.4.0b1 https://pypi.python.org/packages/source/s/scdl/scdl-1.4.0b1.tar.gz

but always found this error

Downloading/unpacking mutagen (from scdl==v1.4.0b1)
  Using version 1.30 (newest of versions: 1.30, 1.29, 1.28, 1.27, 1.26, 1.25.1, 1.25, 1.24, 1.23, 1.22, 1.21, 1.20, 1.19, 1.18, 1.17, 1.16)
  Downloading mutagen-1.30.tar.gz (890kB): 
  Downloading from URL https://pypi.python.org/packages/source/m/mutagen/mutagen-1.30.tar.gz#md5=2c2069bd6a8245f99845f160da37f2ac (from https://pypi.python.org/simple/mutagen/)
...Downloading mutagen-1.30.tar.gz (890kB): 815kB downloaded
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1198, in prepare_files
    do_download,
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1376, in unpack_url
    self.session,
  File "/usr/lib/python3/dist-packages/pip/download.py", line 572, in unpack_http_url
    download_hash = _download_url(resp, link, temp_location)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 433, in _download_url
    for chunk in resp_read(4096):
  File "/usr/lib/python3/dist-packages/pip/download.py", line 421, in resp_read
    chunk_size, decode_content=False):
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 225, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/share/python-wheels/urllib3-1.7.1-py2.py3-none-any.whl/urllib3/response.py", line 174, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 539, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.4/socket.py", line 374, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 751, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 623, in read
    v = self._sslobj.read(len, buffer)
ConnectionResetError: [Errno 104] Connection reset by peer

correct me if i did something wrong

**Comment by zaibfridi** [comment]
okay now i did this 

sudo pip3 uninstall scdl

python3 setup.py install

pip3 freeze is

Brlapi==0.6.1
Magic-file-extensions==0.2
Mako==0.9.1
MarkupSafe==0.18
apturl==0.5.2ubuntu4
chardet==2.2.1
checkbox-ng==0.3
checkbox-support==0.2
colorama==0.2.5
command-not-found==0.3
defer==1.0.6
devscripts==2.14.1ubuntu0.1
docopt==0.6.2
feedparser==5.1.3
friends==0.1
fudge==1.0.3
html5lib==0.999
httplib2==0.8
language-selector==0.1
louis==2.5.3
lxml==3.3.3
mutagen==1.30
oauthlib==0.6.1
onboard==1.0.0
oneconf==0.3.7.14.04.1
piston-mini-client==0.7.5
plainbox==0.5.3
pycrypto==2.6.1
pycurl==7.19.3
pygobject==3.12.0
pyparsing==2.0.1
python-apt==0.9.3.5ubuntu1
python-debian==0.1.21-nmu2ubuntu2
pyxdg==0.25
requests==2.7.0
scdl==v1.4.0b1
simplejson==3.8.0
six==1.5.2
software-center-aptd-plugins==0.0.0
soundcloud==0.4.1
termcolor==1.1.0
ubuntu-drivers-common==0.0.0
ufw==0.34-rc-0ubuntu2
unattended-upgrades==0.1
unity-scope-audacious==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-clementine==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-gdrive==0.7
unity-scope-gmusicbrowser==0.1
unity-scope-gourmet==0.1
unity-scope-guayadeque==0.1
unity-scope-manpages==0.1
unity-scope-musique==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
unity-tweak-tool==0.0.6
urllib3==1.7.1
usb-creator==0.2.23
wget==2.2
wheel==0.24.0
xdiagnose==3.6.3build2
xkit==0.0.0

still the same issue

**Comment by zaibfridi** [comment]
this works 
scdl -l <track_url>
scdl --version is v1.4.0b1
i miss something ???

**Comment by flyingrub** [comment]
i think there is a bug in the soft ... I will try later.

**Comment by Spotlight0xff** [comment]
Works here with your token.
Check if you have anything else in the token line. (btw it broke here when I had 'token = xxx #github' in the line)
And you can add after the line 203 in scdl.py "print(client.options)" (w/o the quotes ofc) to see, if there are anything else in the token variable.

**Comment by zaibfridi** [comment]
i modify the method in this way and this prints nothing only this on the terminal

Soundcloud Downloader

Starting new HTTPS connection (1): api.soundcloud.com
Invalid token...



def who_am_i():
    """
    display to who the current token correspond, check if the token is valid
    """
    print ("In who am i function...")
    logger.info('In who am i function...')
    global client
    client = soundcloud.Client(access_token='1-126453-90543453-ad62a44de0092c', client_id=scdl_client_id)
    logger.info('this is client variable '+ client)
    logger.info('this is client variable '+ client.Options)


    try:
        current_user = client.get('/me')
    except:
        logger.error('Invalid token...')
        sys.exit(0)
    logger.info('Hello {0.username}!'.format(current_user))
    logger.newline()
    return current_user

**Comment by flyingrub** [comment]
fixed ?

**Comment by zaibfridi** [comment]
No its not !! after many tries i leave this .... can you please briefly
guide me on linux/ ubuntu 14.04 ???

Regards
              Shahzaib

**Comment by flyingrub** [comment]
i cannot reproduce your bug nor understand it.
```
Soundcloud Downloader

Hello Zaib Fridi!

Retrieving all the track of user Zaib Fridi...
Retrieved 403 tracks
n°1 of 403 is a track
Found a track
^C^C
Good bye!
```

**Comment by flyingrub** [comment]
still cannot reproduce, seems not related to my soft.
