### ISSUE TITLE
Keep tracks order and also ensure uniqueness

### ISSUE THREAD

**Issue by davidfischer-ch** [flyingrub/scdl#82]
Maybe an idea to both keep insertion order and uniqueness by implementing this:
https://docs.python.org/dev/library/collections.abc.html

    class ListBasedSet(collections.abc.Set):
         ''' Alternate set implementation favoring space over speed
             and not requiring the set elements to be hashable. '''
         def __init__(self, iterable):
             self.elements = lst = []
             for value in iterable:
                 if value not in lst:
                     lst.append(value)
         def __iter__(self):
             return iter(self.elements)
         def __contains__(self, value):
             return value in self.elements
         def __len__(self):
             return len(self.elements)

    s1 = ListBasedSet('abcdef')
    s2 = ListBasedSet('defghi')
    overlap = s1 & s2            # The __and__() method is supported automatically

**Comment by flyingrub** [comment]
i don't know why there would be duplicate track : you can't like or repost a song two times. And the script already handle the case where a track already exist with the -c option. :)
This implementation will slow down the script speed for not enough value i think...
