### ISSUE TITLE
Error trying to set the tags...

### ISSUE THREAD

**Issue by kretash** [flyingrub/scdl#92]
Every time i download a song it failes to set the tags, I don't know if I'm doing anything wrong.

Is there another step i have to do to set the tags?

I'm on windows btw.

**Comment by Darkefyre13** [comment]
on ubuntu i had to run it as an admin level program, so try running through a cmd window with admin privilages?

**Comment by kretash** [comment]
Nope, it still fails to set them.

C:\Users\Hephaestus\Music>scdl -l https://soundcloud.com/hucci/aperfectstorm
[37mSoundcloud Downloader[0m
[37m[0m
[37mFound a track[0m
[37mDownloading A Perfect Storm[0m
100% [..........................................................................] 4259839 / 4259839[37m[0m
[37mSettings tags...[0m
[31mError trying to set the tags...[0m
[37m[0m
[37mA Perfect Storm.mp3 Downloaded.[0m
[37m[0m

**Comment by kretash** [comment]
I'm not sure what this was supposed to do but commenting it cleaned all that garbage in the output.

logger.addFilter(utils.ColorizeFilter())

probably not available for windows.

**Comment by jmcken8** [comment]
It's an issue with the temporary jpg that's being downloaded, the output location is hard coded to /tmp which doesn't exist in windows. Should probably use the 'tempfile' module instead.

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/1e8de9f72a252ea8c789d2ffa879513dba9b373a should fix it.
