### ISSUE TITLE
curl - malformed url

### ISSUE THREAD

**Issue by JonnyTischbein** [flyingrub/scdl#96]
When I try to download a single song/set, I got an curl error.

    curl: (3) <url> malformed

I'm using curl 7.45.0 with following plugins

    libcurl/7.45.0 OpenSSL/1.0.2d zlib/1.2.8 libidn/1.32 libssh2/1.6.0
    Protocols: dict file ftp ftps gopher http https imap imaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp 
    Features: AsynchDNS IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets 

I'm using

    4.2.5-1-ARCH x86_64 GNU/LINUX

Do I need to install an additional lib / plugin ? Or are they just some undownloadable songs ? I just tried a few and got every time the same error.

**Comment by eduardtibet** [comment]
The same here.
```
curl 7.38.0 (x86_64-pc-linux-gnu) libcurl/7.38.0 OpenSSL/1.0.1k zlib/1.2.8 libidn/1.29 libssh2/1.4.3 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp scp sftp smtp smtps telnet tftp 
Features: AsynchDNS IDN IPv6 Largefile GSS-API SPNEGO NTLM NTLM_WB SSL libz TLS-SRP 
```
on 
```
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
```
Seems to be the url extracted are changed in the way the curl doesn't support it. Need some more investigation.

**Comment by eduardtibet** [comment]
@JonnyTischbein  I've finally got the reason for this issue. The problem is that you use previous "bash-styled" version of scdl. I've also used it. But is was deprecated a while go. Try to use .py version (just build it before) and issue will be gone.

**Comment by eddieberklee** [comment]
![asdf](https://cloud.githubusercontent.com/assets/1836653/11890792/3f116272-a50d-11e5-858e-18c9d96119c5.png)

Hmm I'm using the Python version and this seems to still be occurring

**Comment by eduardtibet** [comment]
@eddieberklee, I'm not sure, that you are using python version. The CLI messages that you have at screenshot mentioned are from bashed version. There are no header (in dashed) in py version. Anyhow in my case the cli interface is completely differs from yours. Really!

Anyway, try scdl --version. I have v1.3.2

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/blob/master/scdl/__init__.py#L5 the latest version is : 'v1.4.0b1'
